### PR TITLE
[db] support compilation album view

### PR DESCRIPTION
**Pull request by whatdoineed2do**
This PR is for functionality to represent compilations as a single entity in an "album view" on web front end; currently compilation albums are listed as multiple entries (one per artist)
https://github.com/ejurgensen/forked-daapd/issues/642

An example music library with dummy sound, incls a file with MusicBrainz tagged meta
[music-library.tar.gz](https://github.com/ejurgensen/forked-daapd/files/2789070/music-library.tar.gz)

It'd be great to have feedback on this approach and the points raised below.
 
---
This PR is in 3 sections:

DB + meta handling
- `compilation id` column to store the underlying meta
- `songalbumid` is used to store `compilation id` hash when available, overriding `album artist name` + `album name`
- changes to the group album/artist query;  these album query can now return multiple artists for a given album (ie compilation where `album artist` == `artist`) as comma separated list of `songartistid`
- artist searches updated to take comma list of `songartistid`s
- ffmpeg scanning for finite list of identifying "compilation" tags

JSON
- presentation for `artist` object updated to include `items[]` for each artist info as well as the preferred `artist_name` for reference that is useful in case of compilation (currently hardcoded to be `Various Artists` but could be based on cfg) or for non-compilations being just `album artist`
- `api/library/artist` endpoints can take comma separated list of artist ids (as provided from db that represents the artists in a compilation)
- new `api/library/artist/.../tracks` endpoint that replaces our existing "tracks for artist" search via SMARTQL as to provide support for multiple artists search

Web src
- updates to handle multiple artists returned on `artist page` and `artists's tracks page` and the track counts etc

One point to note is the multiple comma separated list of artist ids from the DB query and subsequent upds to json api  - I don’t think there's another way to fit into the current setup of the browse/sort clause structures.  This same comma separated list is then used opaquely by the web front end to request further info from the json api which I've had to extend.

### CODE REVIEW

**Comment by ejurgensen** [comment]
I finally had time to take a look at this PR, it took some months unfortunately. I think the tags you propose including would be great to support, because that way forked-daapd can really make the most of the data that a well-tagged library provides.

I'm not too happy about the compilationid field. It seems to have significant overlap with the songalbumid field. To me it is odd to map for instance the "MusicBrainz Album Id" to compilationid, and not to songalbumid.

I'm also worried about performance impact of the altered SQL query, plus the complexity of the query. It is important that it is tuned to the indices (or that the indices are tuned to the query).

So I've made a branch with a simplified approach, where filescanner_ffmpeg.c can set songalbumid based on available metadata. No new db fields. I've tested it with the files you provided, and it looked ok, but to be honest the original issue description (issue #642) is rather long and I didn't read up on it, so perhaps I am overlooking something. Still, I would like you to test the branch, and if it is ok then rebase if there are further changes (JSON/web) that you would like to add. The branch is https://github.com/ejurgensen/forked-daapd/tree/album_meta1.

**Comment by whatdoineed2do** [comment]
Thanks; your branch lets us group albums as I had done with `compilationid`.  I've rebased with your changes (not yet pushed) but we would still need the updates to the queries - i'm summarising/formatting them below so its easier to see the changes:


When looking up an album, we currently get back the single `songartistid` - for compilations, this could very well be the hash for `Various Artists` or it could be `album_artist` == `artist`.

On the web ui we use the `songartistid` to be able to look up the other ablums belonging to this artist on the current album;  for compilations, it would be useful to lookup albums for all artists in the album which would be supported by returning a comma seperated list of `songartistid`.  This would not require any additional indexes since its just using `album_artist` field which is correctly indexed.

`db_build_query_group_albums()`
```
             "SELECT g.id, g.persistentid, 
 	            f.album, f.album_sort, 
 		    COUNT(f.id) as track_count, 
-		    1 as album_count, 
-		    f.album_artist, 
-		    f.songartistid, 
+		    COUNT(DISTINCT f.songartistid) as artist_count, 
+		    COUNT(DISTINCT f.songalbumid) as album_count, 
+		    CASE WHEN COUNT(DISTINCT f.songartistid) > 1 THEN '--' ELSE f.album_artist END as album_artist, 
+		    GROUP_CONCAT(DISTINCT f.songartistid) as songartistid, 
 		    SUM(f.song_length) 
 	       FROM files f JOIN groups g ON f.songalbumid = g.persistentid %s 
 	   GROUP BY f.songalbumid %s %s %s;", qc->where, qc->having, qc->order, qc->index);
```

Similar for the artists handling `db_build_query_group_artists()`
```
     "SELECT g.id, g.persistentid, 
 	    f.album_artist, f.album_artist_sort, 
 	    COUNT(f.id) as track_count, 
+	    COUNT(DISTINCT f.songartistid) as artist_count,
 	    COUNT(DISTINCT f.songalbumid) as album_count, 
-	    f.album_artist,
-	    f.songartistid, 
+	    GROUP_CONCAT(DISTINCT f.album_artist) as album_artist,
+	    GROUP_CONCAT(DISTINCT f.songartistid) as songartistid,
 	    SUM(f.song_length) 
        FROM files f JOIN groups g ON f.songartistid = g.persistentid %s 
     GROUP BY f.songartistid %s %s %s;", qc->where, qc->having, qc->order, qc->index);
```

Do these mods still raise concerns?

**Comment by ejurgensen** [comment]
I made a few performance tests on my RPi2, and the changes to the two queries increase the execution time with a factor 2x - 3x. So they are not acceptable.

**Comment by whatdoineed2do** [comment]
I remember doing the timings a while back and they weren't as bad as 2-3x.  I took another look on my RPi3 where the library file is on a USB connected (spinning) disk with a library of about 3,500 in `files` table:  the different quieries were run in different sqlite sessions to avoid one being influenced by caching and these are the best/worst of a series of 10runs

* artists query (new vs old)

Run Time: real 0.265 user 0.244006 sys 0.020144
Run Time: real 0.284 user 0.263562 sys 0.020220

vs 

Run Time: real 0.192 user 0.186203 sys 0.003014
Run Time: real 0.181 user 0.179230 sys 0.000243

* albums (new vs old)

Run Time: real 0.228 user 0.217679 sys 0.009986
Run Time: real 0.260 user 0.259328 sys 0.000248

vs

Run Time: real 0.190 user 0.167141 sys 0.019780
Run Time: real 0.227 user 0.223749 sys 0.000207

Admittedly still slower.  Without the group_concat then we lose the (proposed) ability to drill down on all artsts that are in the album but perhaps that info can be retreived as a separte db call that would leave these baseline album and artist calls alone.

Would that be acceptable?

**Comment by ejurgensen** [comment]
I can’t say what is causing the degradation but here’s how I tested so you can perhaps reproduce:
- library of 2500 items 
- caching disabled
- album and artist views 
- client Apple Remote
- RPi2, db on ramdisk
- check DAAP response times from log

If removing the concat fixes performance it would be fine.

**Comment by whatdoineed2do** [comment]
On the RPi3 the performance is ok but RPi2 does show some issues.

For the test, I copied the db file to a RPi tmpfs, `pragma cache_size = 0` and ran the queries multiple times and these are the averages:  Looking at the query plan, its the `COUNT(DISTINCT...)` that are adding to the timings... I'll have to think if theres anything more that can be done otherwise we may end up with a partial soln.

RPI3

|Category|Timing old|Timing new|increase|
|-|-|-|-|
|artist|0.22|0.305|  +38%|
|albums|0.23|0.295| +29%|

RPI2

|Category|Timing old|Timing new|increase|
|-|-|-|-|
|artist|0.331|0.456|  +38%|
|albums|0.224|0.515| +130%|

----
* artist - old
```
SELECT g.id, g.persistentid, f.album_artist, f.album_artist_sort, COUNT(f.id) as track_count, COUNT(DISTINCT f.songalbumid) as album_count, f.album_artist, f.songartistid, SUM(f.song_length) FROM files f JOIN groups g ON f.songartistid = g.persistentid WHERE f.disabled = 0 AND (f.media_kind = 1) GROUP BY f.songartistid  ORDER BY f.album_artist_sort, f.album_sort, f.disc, f.track ;
```
* artist - new
```
SELECT g.id, g.persistentid, f.album_artist, f.album_artist_sort, COUNT(f.id) as track_count, COUNT(DISTINCT f.songartistid) as artist_count, COUNT(DISTINCT f.songalbumid) as album_count, GROUP_CONCAT(DISTINCT f.album_artist) as album_artist, GROUP_CONCAT(DISTINCT f.songartistid) as songartistid, SUM(f.song_length) FROM files f JOIN groups g ON f.songartistid = g.persistentid WHERE f.disabled = 0 AND (f.media_kind = 1) GROUP BY f.songartistid  ORDER BY f.album_artist_sort, f.album_sort, f.disc, f.track ;
```
* albums - old
```
SELECT g.id, g.persistentid, f.album, f.album_sort, COUNT(f.id) as track_count, 1 as album_count, f.album_artist, f.songartistid, SUM(f.song_length) FROM files f JOIN groups g ON f.songalbumid = g.persistentid WHERE f.disabled = 0 AND (f.media_kind = 1) GROUP BY f.songalbumid  ORDER BY f.album_sort, f.disc, f.track ;
```
* albums - new
```
 SELECT g.id, g.persistentid, f.album, f.album_sort, COUNT(f.id) as track_count, COUNT(DISTINCT f.songartistid) as artist_count, COUNT(DISTINCT f.songalbumid) as album_count, CASE WHEN COUNT(DISTINCT f.songartistid) > 1 THEN '--' ELSE f.album_artist END as album_artist, GROUP_CONCAT(DISTINCT f.songartistid) as songartistid, SUM(f.song_length) FROM files f JOIN groups g ON f.songalbumid = g.persistentid WHERE f.disabled = 0 AND (f.media_kind = 1) GROUP BY f.songalbumid  ORDER BY f.album_sort, f.disc, f.track ;
```

**Comment by ejurgensen** [comment]
I am closing this issue since I think the main issue is fixed. I don't think the remaining improvements to the web UI concerning aggregation warrant the increased complexity and performance deterioration.

**Pull request closed without merging**
