### PR TITLE
Include web interface

### PR DESCRIPTION
**Pull request by chme**
This pr inculdes the web interface from https://github.com/chme/forked-daapd-web ([v0.1.1](https://github.com/chme/forked-daapd-web/releases/tag/v0.1.1)) into forked-daapd.

During configure it is possible to exclude the webinterface with `--disable-webinterface`. The webinterface requires websocket support and can only be enabled if libwebsockets is available. 

If you want to have a quick look at the webinterface and are running a recent version from git, instead of building from this pr, it is also possible to simply extract the files from the [dist-tarball](https://github.com/chme/forked-daapd-web/releases/download/v0.1.1/forked-daapd-web-dist-0.1.1.tar.xz) to the forked-daapd htdocs directory (`/usr/share/forked-daapd/htdocs`) .

### CODE REVIEW

**Comment by LordMyschkin** [comment]
Finally! I have been eagerly waiting for this feature to find its way. I just love to possibility to handle volumes by speaker - ty my knowledge, thats the only "mpd client" doing this.

What I am missing is a way to browse through the directory structure, since my music is organised more in directories than in albums (just better for classical music from my experience) - do you plan to incude that, or did you even do that already and I am missing it?

Thanks again for this great extension and to ejurgensen for allowing it.

**Comment by chme** [comment]
> do you plan to incude that, or did you even do that already and I am missing it?

It is missing, but i have plans to add browsing the directory structure. But that might take a while ... Another feature i like to add is creating/modifying playlists ... and some cover art would be nice ...

> Oh i did the trick with copying the files into an existing recent forked-daapd-build - and the admin.html seems to be lacking, and the old one does not really work....

There should be no conflict with the admin interface (completely separate files). Did you keep all files that were in the htdocs directory and only copied the new ones? Can you give more information about the problems with the admin interface?

**Comment by Porco-Rosso** [comment]
Hi, I'm using a recent git version (v26.0) compiled with support for ffmpeg, iTunes XML, LastFM, Chromecast, MPD, Device verification, Websockets, ALSA, Pulseaudio. I can also confirm the admin interface works. 

I've tried dropping the files into the directory indicated, and although the page loads and occasionally loads some metadata, it says `Connection lost. Reconnecting ...` frequently and seems to stop working.
Is there something I am missing?

**Comment by chme** [comment]
@Porco-Rosso Do you access the webinterface over http://forked-daapd.local:3689 ? If that is the case, could you try to access it with the ip address of your forked-daapd server (instead of "forked-daapd.local")?

**Comment by LordMyschkin** [comment]
@chme 
There seems to  be a problem parsing the file; in the browser, it looks like

forked-daapd
Artists

{{ library.artists }}

Albums

{{ library.albums }}

Songs

{{ library.songs }}

Total playtime

{{ library.db_playtime | duration }}

Status
Library
Update library
Update in progress ...

**Comment by chme** [comment]
@LordMyschkin Looks like loading the javascript files for the admin interface failed. Could you please check if the files "vue.min.js", "axios.min.js" and "forked-daapd.js" are in the htdocs/js folder?

@Porco-Rosso i do not experience issues connecting to the websocket (and i do refresh quite a lot). I guess there is nothing useful in the forked-daapd.log? (The logging of the websocket part in forked-daapd needs some work ... i'll look into this)

**Comment by LordMyschkin** [comment]
@chme: you are completly right; it was my fault, instead of merging the two directories, i replaced the original one with your compressed directrory - which was a mistake....
All corrected now, everything working smoothly again.
Looking forward for directory browsing capabilities, althought maybe only important for me (I can image that would be a piece of work...). Thx again!

**Comment by ejurgensen** [comment]
forked-daapd now has a playback webinterface, excellent work!

**Comment by ejurgensen** [comment]
Can you update the INSTALL file so the documentation covers --enable/--disable-webinterface?

**Comment by ejurgensen** [comment]
I notice lintian has some additional errors/warnings now:
```
E: forked-daapd source: source-is-missing htdocs/js/app.js line length is 32768 characters (>512)
E: forked-daapd source: source-is-missing htdocs/js/manifest.js line length is 799 characters (>512)
E: forked-daapd source: source-is-missing htdocs/js/vendor.js line length is 11574 characters (>512)
W: forked-daapd: duplicate-font-file usr/share/forked-daapd/htdocs/fonts/FontAwesome.otf also in fonts-font-awesome
W: forked-daapd: duplicate-font-file usr/share/forked-daapd/htdocs/fonts/fontawesome-webfont.ttf also in fonts-font-awesome
```
I can't say I understand them completely, but I hope you will check if there is something that should be done.

**Comment by ejurgensen** [comment]
I've been trying the new web interface and it's really awesome! Fantastic work @chme. I think it looks great in a "no non-sense" sort of way, and the icons you have chosen are very nice. I'm also impressed by how many features and views that are already working.

I'm eager to release this to the RPi repo, but I made a stupid typo in the last RPi release which basically means I can't make a new release unless I bump the main version to 26.1. So now I will do that asap. But that means docs have to be in order, and I also have to at least compile test on an array of platforms.

I've updated INSTALL, README.md and the FreeBSD install script, so you can disregard my request above about updating INSTALL. However, it would be great if you can check the lintian errors/warnings above. I might also get back to you if more stuff shows up.

**Comment by chme** [comment]
> E: forked-daapd source: source-is-missing htdocs/js/app.js line length is 32768 characters (>512)
> E: forked-daapd source: source-is-missing htdocs/js/manifest.js line length is 799 characters (>512)
> E: forked-daapd source: source-is-missing htdocs/js/vendor.js line length is 11574 characters (>512)

We only have the compressed and minified javascript files for the webinterface in the forked-daapd source tree. This is why lintian complains it cannot find the source file (https://lintian.debian.org/tags/source-is-missing.html).
Including the source is problematic as there are quite some node modules etc. and building has to be done with node-js. 
From searching the internet it sounds like it is possible to add an lintian overrides file. 

> W: forked-daapd: duplicate-font-file usr/share/forked-daapd/htdocs/fonts/FontAwesome.otf also in fonts-font-awesome
> W: forked-daapd: duplicate-font-file usr/share/forked-daapd/htdocs/fonts/fontawesome-webfont.ttf also in fonts-font-awesome

Adding a dependency to a font-awesome package does not sound good to me. Some packages seem to add an exception to the lintian overrides file for this.

I have no experience with packaging and don't know if adding a lintian overrides file in these cases is fine.

**Comment by ejurgensen** [comment]
Thanks for looking into it. I'll cut a 26.1 release based on current master. We'll see what the Debian maintainers say, it would be them that might have reservations.

**Pull request merged**
