### PR TITLE
[mpd] add support for speaker (de)activation 

### PR DESCRIPTION
**Pull request by chme**
This pr implements support for the mpd commands to control speakers (outputs). 
Following commands are supported:
* disableoutput
* enableoutput
* toggleoutput

Sadly the existing speaker (raop) id can not be used, as it is to large for mpd. I introduced a "num" for each speaker, that gets simply incremented if a new speaker gets added to the device list.

The mpd protocol only allows to activate or deactivate a speaker (output), setting volume for a specific speaker is not supported.

### CODE REVIEW

**Comment by ejurgensen** [comment]
It seems you could use a shortened id in mpc.c? - instead of introducing a new id? I think I would prefer that.

**Comment by chme** [comment]
The current raop-id is extracted from the avahi service announcement of the speaker (player.c, raop_device_cb). I am not familiar with this part of forked-daapd, so i did not dare to change it and instead went for the easier approach to introduce a new id field.

Debugging shows that in raop_device_cb the name parameter contains for example "B418D1DDB471@Wohnzimmer". The hex number part "B418D1DDB471" then gets converted to the uint64_t raop-id. I do not think changing from uint64_t to a smaller id would work, what do you think?

**Comment by ejurgensen** [comment]
I didn't mean shortening the id globally, just in mpc.c. Something like this, I guess:
- in speaker_enum_cb() set outputid=(unsigned int)id
- in while-loops in the command handlers (disableout, enableoutput and toggleoutput) you match the incoming argument id against "(unsigned int)output->id"
- and then just remove num

Hope that makes sense. This disregards half the id, of course, but I would think that is unlikely to cause problems.

**Comment by chme** [comment]
I changed it like you suggested. Using unsigned int caused problems, but using unsigned short works. At least my two airplay speakers got different (short) ids and enabling/disabling through mpc works.

**Comment by snizzleorg** [comment]
how do I check the speaker ids with via mad? I tried mpc outputs but that didn't give any results. Which mad client are you using for testing?

**Comment by snizzleorg** [comment]
Sorry. I had a old version. the most recent gives the outputs....

**Comment by chme** [comment]
I am using mpc (version 0.25) for testing. To issue single commands specified by the mpd protocol, i am using the python library "python-mpd2". The more advanced mpd clients like MPDroid for android or ncmpccp are not yet working so well. The main problem is the missing implementation for the "idle" command (notifies about library and play status changes) in forked-daapd. I am still working on that one.

**Pull request merged**
