### PR TITLE
Updated configure/makefiles related to Issue #327

### PR DESCRIPTION
**Pull request by sshambar**

### CODE REVIEW

**Comment by ejurgensen** [comment]
Wow, very interesting work you have done here. I will look into it and test on a few platforms. May I ask how you have acquired this knowledge of build scripts? I have always found them kind of obscure...

**Comment by sshambar** [comment]
I encounter broken autoconf so often, that I finally decided to learn why (forked isn't broken, but it didn't support vpath builds, self contained dist, and distcheck).  I also spent quite a while fixing bootstrap/libtool to handle "non-standard paths" (eg with spaces etc, still haven't finished that work :), so got a good start at portable shell programming there...

The info files for m4/autoconf/automake and aclocal are actually very good references, and I found a weekend to sit down and slog through them - the macro index is especially useful.  Also using some of the GNU packages as a guide to "best practices" and checking out discussions on stackoverflow for especially sticky issues :).

The rpm spec file was a little more difficult as the rpm.org documentation isn't comprehensive, and I needed to check out quite a few complex spec examples (like NetworkManager and octave).

**Comment by ejurgensen** [comment]
Cool, and very lucky for forked-daapd to be able to benefit from your studies. A few more questions:
1. Which platforms have you tested the modified build scripts on?
2. TBH, I don't really know what the libunistring macros do. They are quite old, so perhaps they aren't even necessary any more. Have you looked into that? I wouldn't mind getting rid of them, if that is an option.

**Comment by sshambar** [comment]
I've built on several machines/VMs running Fedora with a mix of devel/library/tools removed to validate the tests and build configurations (including nothing enabled/all enabled).  I also have a (slightly extended) version running on OSX where I'm working on getting replacement mDNS, clock and fsevents patches working... (and requires a real config.rpath).  I haven't tested on Debian yet (don't have enough libraries installed), but there's no reason it should function differently as that's point of writing with macros not shell code :)

The unistring macros just test for libunistring w/ and w/o libiconv... it would be trivial to cut out the relevant tests into configure.ac as most of the version checking logic isn't really necessary for forked...

**Comment by ejurgensen** [comment]
Tried a test of the build scripts on FreeBSD 10.1, it gives the following build error (after I had taken care of another issue in mdns_avahi.c): [freebsd_10_1.build.txt](https://github.com/ejurgensen/forked-daapd/files/677672/freebsd_10_1.build.txt)

Interestingly, this only happens on the first build. If I retry it succeeds.

**Comment by sshambar** [comment]
Yes, found that porting issue when was building on freebsd 9.3 today (non-GNU sed is a little more picky on script format).

I've also been working on cleaning up the configure checks, and updated them to support
porting to OSX.  Some required headers weren't actually "required" by configure, and some checks were duplicates.  I've also fixed some bugs when libraries (ffmpeg) are in "non-standard" locations (but found by pkg-config).  Also found a few issues on freebsd 9.3 and when using libav (not ffmpeg) that required some tweaks.

I've pushed a new commit to the fixconfig branch which you can checkout... I'm guessing github may update the pull request automatically?

**Comment by ejurgensen** [comment]
Yes, they should update the pull request automatically, but it seems not to work right now. Probably because I have detached my fork of forked-daapd so that it is now parent. For some reason all the forks of my repo didn't follow, so now your fork is of the wrong repo. I have written to Github support about that.

I will add a few comments to your recent changes.

**Comment by sshambar** [comment]
I checked all the comments, and responded to them all :)

I worked on porting to OSX last night, and have it build (testing next!).  Much of the freebsd code works on OSX (kqueue), but had to code replacements for clock_ and timer_ functions using mach calls.  Added a few tests for kqueue, timer and mach, pthread and endian functions to get it all working -- I'll push it when I've verified it all works, and doesn't break linux/freebsd!

**Comment by sshambar** [comment]
Re github... yeah, my fork is now based on some other clone from CBGoodBuddy or something, so I guess the pull isn't in sync anymore.  I can re-fork and issue a new pull if necessary.

**Comment by sshambar** [comment]
Oh, and I'd be happy to migrate off libunistring.m4 -- it doesn't support specific env variable overrides, and so is a pain to work with on OSX (wish it supported pkgconfig :)

**Comment by ejurgensen** [comment]
Impressive if you manage to build and run on osx. I think a few people have made attempts, but I don't know of anyone succeeding.

I think getting off the libunistring macro would be good. Probably best to do it in a separate PR, though. The same goes for the osx modifications if they are extensive.

**Comment by sshambar** [comment]
Been busy on the holiday :) - I've moved much of the library/pkgconfig and feature checks into custom macros, and greatly simplified the maintenance of the configuration and makefiles; these checks include function/header checks for each library which ensure the supplied flags actually work - and in the process found some that were broken when libraries were installed in custom locations (eg json-c includes, others missing cflags/libs).  Also fixed chromecast/spotify on freebsd, and included lots of additional checks that I have used in my OSX port (but none of that code, that's going to be a different patch!).  There's actually tons of additional updates too - check the head of my fixconfig branch for details.   I've tested extensively on freebsd, osx (with the extra code) and various linux machines, please let me know if you find a way to break any of it.

**Comment by sshambar** [comment]
Minor update, removed a test variable left in configure

**Comment by ejurgensen** [comment]
Absolutely awesome. I've made a quick test on both my Ubuntu dev machine, and then, to make things a bit more difficult, on OpenWrt, and both built fine :-)

A few remarks and questions:
1. Currently, pregenerated antlr files are supposed to be placed in /src/pregen, and in fact that is used for building on OpenWrt's own build machines, because they don't have antlr. So that build would fail with this. I guess the build could be changed to place the pregenerated files in /src, where you are looking for them, but I would like to know why you removed support for /src/pregen?
2. Those 684 lines of new script in config.rpath kind of bum me out... and tbh it is probably because I don't really understand them. Perhaps, if you could let me know what they are doing and why they are necessary, I could learn to love them?
3. Between every gcc compile line there is now a "mv -f $depbase.Tpo $depbase.Po"-line. What is that?

**Comment by sshambar** [comment]
A few answers :)
1. I played around with the pregen for quite awhile before landing on the current solution.  Basically, the antlr3 and gperf products should be considered maintainer files (like the configure script etc), and  distributed so that most people don't need antlr and gperf to compile.  If you use 'make dist' the autotools will create a tarball that includes all the files that you need to perform a './configure; make' on any machine with only the most basic devel headers and no tools (antlr, gperf, autoconf etc)... this should include openwrt!  It's also how I configured the rpm spec file, so the tarball can be used with 'rpmbuild -tb <tarball>' without requiring gperf or antlr on the build machine.
2. config.rpath is a standard file from gnulib, but isn't installed with autoreconf -i as most people don't have gnulib installed (but the file needs to exist).  However, I found porting to OSX that it actually needs to work on systems with non-gnu linkers, so I included a real one so linking now works on those systems :).  It's just a copy of the gnulib one.
3. .Po files are just autotools dependency files... they're created if you have automatic dependencies enabled (which they are by default by configure)... the mv is just autotools being safe by creating a tmp file and moving it into place if after the source compiles (those were probably there before unless you had auto-dependency off before, or had silent builds enabled...)

**Comment by ejurgensen** [comment]
I will run it through some of my vm's to test. Let me also ping some of the people who have built forked-daapd (or tried to) on different platforms. Don't know if they are still interested, but if any of them are willing to test this change it would be good. I could find:

1. Docker @snizzleorg and @sparklyballs
2. Arch Linux @gillecaluim
3. Synology @Trauma

About the other things: Can you think of alternatives to copying the config.rpath? Having it in the forked-daapd code base means I have to maintain it, I'm not thrilled about that. About the copying of Tpo: I understand it was also there before, but silenced? Is it possible to silence it again?

**Comment by ejurgensen** [comment]
Result from FreeNAS 9.10 - configure could not find libunistring. See this log:
[config.log.txt](https://github.com/ejurgensen/forked-daapd/files/691546/config.log.txt)

**Comment by sparklyballs** [comment]
what do you need me to test ?

**Comment by ejurgensen** [comment]
Check if you can build this branch of sshambar's repo: https://github.com/sshambar/forked-daapd/tree/fixconfig

**Comment by sparklyballs** [comment]
@ejurgensen 

[jenkins build log](http://jenkins.linuxserver.io:8080/job/Dockers/job/LinuxServer.io/job/linuxserver-daapd-branch/1/console)

[Dockerfile for the branch](https://github.com/linuxserver/docker-daapd/blob/test_build_sshambar/Dockerfile)

docker pull linuxserver/daapd:test_build_sshambar

**Comment by sshambar** [comment]
@ejurgensen 

FreeNAS 9.10: I'm guessing libunistring is in a non-standard location?  I have all the library macros working the same as the pkg-config macros... so any library that isn't installed in the default path can be configured with <ENV_PREFIX>_CFLAGS/_LIBS (eg LIBUNISTRING_CFLAGS/_LIBS).  You might have the old macro variables set (INCUNISTRING and LIBUNISTRING), or the old config args  --with-libunistring-prefix

config.rpath: Actually, since we don't use the libunistring.m4 macros anymore, we probably don't need a working config.rpath (it's needed by the gettext library tests which libunistring used) -- AM_ICONV still uses it, but as long as iconv is installed in a standard location, configure should be ok on systems with odd library extensions (osx etc) -- I'll push an empty file.

**Comment by ejurgensen** [comment]
Glad to hear config.rpath can go.

It seems libunistring is in the standard location for FreeNAS (/usr/local/lib and /usr/local/include), and I didn't set any special flags for libunistring. I didn't do that before either. Even if I do now set the flags with the locations it fails. I will look into it some more tomorrow.

**Comment by sshambar** [comment]
OK, played around with FreeBSD a bit, and it looks like the library search that libunistring.m4 used (same as iconv) additionally searched $prefix/lib for the library, and linked against it if it found it (which requires a working config.rpath to work on non-gnu systems).  The search in the new macros just uses the linker default path...(or one provided by env variables).  I could add a fallback to check using $prefix/{include/lib} in the flags if the default path doesn't find the library, which should solve the same problem without re-requiring config.rpath?

**Comment by ejurgensen** [comment]
Sounds good to me. I looked at FreeNAS some more today, but wasn't able to determine the cause, so I'm glad you are on to it.

**Comment by sshambar** [comment]
Updated the function checks to look under the $prefix directories!  I also updated the macros so they can all be expanded recursively even for the same library, and updated the unistring library check to try adding iconv if initial tests fail (like the original code did).

**Comment by ejurgensen** [comment]
I can confirm this fixed the libunistring issue on FreeBSD, but now the next step, finding zlib, fails. Even if I manually set ZLIB_CLAGS/LIBS. Let me know if you need a config.log to look into this?

**Comment by sshambar** [comment]
I had to use env variables for zlib on FreeBSD too (no pkg-config for it there)... You need to have both vars set for PKG_CHECK_MODULES to work;  I used ZLIB_CFLAGS=-I/usr/include and ZLIB_LIBS=-lz - if you can't get that to work, could you post the config.log and the location of your libz.{a,so} and zlib.h?

**Comment by ejurgensen** [comment]
Ok, it works if I give the vars directly as arguments to configure. The problem was that I was using the [script](https://github.com/ejurgensen/forked-daapd/blob/master/scripts/freebsd_install_10.1.sh#L86), where ZLIB_XX are exported. This worked before. I also now need to specify -lz, which as you can see in the script was not required before. Any chance the old behaviour can be kept?

**Comment by sshambar** [comment]
Cool feature of the new macros are that they catches errors like the one I see in this script... You actually aren't providing the correct values for ZLIB_LIBS -- the PKG_CHECK_MODULES macro trusted that if you supplied <library>_CFLAGS/_LIBS that they were correct, and used them blindly.  My new macro enhances those checks by actually validating that they can be used compile and link a function/header we use (which catch these errors).  ZLIB_LIBS should be "-lz" (or "-L<dir> -lz" if <dir> isn't in the default link path)... the final program compiles only by side effect, since at least one of the libraries we link with (eg libavcodec) recursively link with libz - but we shouldn't rely on that in case it changes.

**Comment by ejurgensen** [comment]
Well it still fails if I set ZLIB_LIBS="-L/usr/lib -lz" in the script. Also if it is just set to -lz.

**Comment by sshambar** [comment]
That sounds like a problem :) -- can you post the config.log?

**Comment by ejurgensen** [comment]
Oops, found the problem: My script was missing #!/bin/sh. Works just fine now with the exports...

Will merge it now. Thanks a million for letting this project benefit from your insights, and I'm looking forward to your os x work.

**Comment by couteau** [comment]
@sshambar I'd be interested to see your OS X code. I've been working on my OS X branch and finally got it to compile and do simple browsing/streaming to iTunes. I've only tried it without any of the extras enabled -- no spotify, mpd, etc., and I used homebrew for most of the dependencies. It's in my fork and I just rebased it to ejurgensen's current master. I saw some of what you changed to deal with OS X in this pull request, but didn't see some of the other things I had to do to make it work.

**Comment by sshambar** [comment]
@couteau I have it all compiled and running, but got distracted for awhile by random crashes which turned out to be mutex related (see fixthreads branch). I should probably submit what I have and you can check it out... I have clock/timer replacements and Bonjour integration so far...

**Comment by sshambar** [comment]
I've submitted pull request #335 - this is a branch off fixthreads that includes all the OSX fixes I've been working on. It compiles and runs (no guarantees on all the functions working though :)

**Comment by ejurgensen** [comment]
Hi @sshambar, I ran into an issue coming from this PR while trying to build for oldish Wheezy. Hope you can check it out. The problem comes from commit 8b4b55b, where the modified src/Makefile.am creates a bash syntax error. Here is the error:

```
/usr/bin/gperf --output-file=dacp_prop_hash.h dacp_prop.gperf
/usr/bin/gperf --output-file=dmap_fields_hash.h dmap_fields.gperf
/bin/bash: -c: line 0: syntax error near unexpected token `||'
/bin/bash: -c: line 0: `|| echo "  GEN     " RSP.g "products"'
Makefile:926: recipe for target 'RSPLexer.c' failed
make[3]: *** [RSPLexer.c] Error 1

```

**Comment by sshambar** [comment]
That change was to support silent rules, which are enabled by default in automake 1.13+ (and can be enabled in older automakes as an option.  I could fix it several ways, but a few questions:
1. How old is the automake on Wheezy?
2. How old automake do you want to support?  If older than 1.11 then I'll need to either remove the silent rule logic, or add some macros/logic to work around older versions...
3. I might be useful to for me to add the oldest supported automake in AM_INIT_AUTOMAKE... if you know the oldest you want to support.

Let me know what you want to do and I'll amend the patch :)

**Comment by ejurgensen** [comment]
It looks like Wheezy has 1.11, so if you can amend to support that it would be fine, I think.

**Comment by sshambar** [comment]
OK, I've pushed an update to fixconfig that should work on automake as early as 1.11.  I modified the custom antlr silent rules as suggested in the automake docs in place of AM_V_P, as that appears to only be available in 1.12+

Do I need to open a new pull request, or can you reuse this one?

**Comment by ejurgensen** [comment]
Thanks for the quick fix! I have put it into master right away.

BTW, consider updating the libav/ffmpeg dual install pr so it is mergable.

**Pull request merged**
