### PR TITLE
Update player web interface (v0.5.0)

### PR DESCRIPTION
**Pull request by chme**
- Support links to album, artist and genre from queue item modal (#686)
- Improve podcasts views in player web interface (#689)
- Add play stream option in menu (pr #693)
- Add button to open details dialog in artist/album/playlist views (pr
#693)
- Fix links to genre page (pr #693)
- Update dependencies

This update also contains a new version of bulma (0.7.1 -> 0.7.4) and vue (2.5.22 -> 2.6.6). I'll do some more testing over the week and will merge after that, if there are no issues.

### CODE REVIEW

**Comment by whatdoineed2do** [comment]
I think I've hit a problem with 3b718ffb16f2d3903efe38228e6c3959e5a4f7b5 on IOS.  With this applied it breaks the webui on all my IOS devices - nothign is displayed when we hit the webui.

I've build this via `npm run dev` and `npm run build` - as soon as this is applied IOS browser just gets a blank screen hitting `192.168.0.103:8080` BUT its fine using firefox from my dev machine (where npm dev is running)

**Comment by whatdoineed2do** [comment]
One more: typo in 99e0cfe6bbda7aa7491cac241c23a4b5d6ff79d2, should be:
```
diff --git a/web-src/src/components/ModalDialogQueueItem.vue b/web-src/src/components/ModalDialogQueueItem.vue
index 157d3ed0..2485df23 100644
--- a/web-src/src/components/ModalDialogQueueItem.vue
+++ b/web-src/src/components/ModalDialogQueueItem.vue
@@ -103,7 +103,7 @@ export default {
     },
 
     open_genre: function () {
-      this.$router.push({ name: 'Genre', params: { genre: this.item.name } })
+      this.$router.push({ name: 'Genre', params: { genre: this.item.genre } })
     }
   }
 }
```

**Comment by chme** [comment]
Thanks for testing and reporting! 

I found this stackoverflow answer searching for Safari and web audio api problems: https://stackoverflow.com/questions/46363048/onaudioprocess-not-called-on-ios11/46534088#46534088

I may get my hands on a macbook tomorrow and hopefully can find out if that solves the problem. 
This is the change i have in mind:

```
diff --git a/web-src/src/audio.js b/web-src/src/audio.js
index 96c6325..f88a9e2 100644
--- a/web-src/src/audio.js
+++ b/web-src/src/audio.js
@@ -4,12 +4,14 @@
  */
 export default {
   _audio: new Audio(),
-  _context: new AudioContext(),
+  _context: null,
   _source: null,
   _gain: null,
 
   // setup audio routing
   setupAudio () {
+    var AudioContext = window.AudioContext || window.webkitAudioContext
+    this._context = new AudioContext()
     this._source = this._context.createMediaElementSource(this._audio)
     this._gain = this._context.createGain()

```

**Comment by whatdoineed2do** [comment]
Let me try to patch my local dev instance with this later tonight and report back.  This was a problem on both iphone IOS 12 and ipad IOS 10

One thing to note though, I did see on https://developer.mozilla.org/en-US/docs/Web/API/AudioContext that `Safari on IOS` (on mobile) capability is *very* patchy/unconfirmed functionality for `AudioContext`... and different to ability of `Safari on desktop`.

**Comment by whatdoineed2do** [comment]
Seems to have done it.  I checked out `master`, started `npm run dev` and connected to the web ui from my iphone - nothing shown.  I applied the 4 changes below and reconnected with my iphone and the web ui loads.

I haven't tested anything else but your patch is good.

> ```
> diff --git a/web-src/src/audio.js b/web-src/src/audio.js
> index 96c6325..f88a9e2 100644
> --- a/web-src/src/audio.js
> +++ b/web-src/src/audio.js
> @@ -4,12 +4,14 @@
>   */
>  export default {
>    _audio: new Audio(),
> -  _context: new AudioContext(),
> +  _context: null,
>    _source: null,
>    _gain: null,
>  
>    // setup audio routing
>    setupAudio () {
> +    var AudioContext = window.AudioContext || window.webkitAudioContext
> +    this._context = new AudioContext()
>      this._source = this._context.createMediaElementSource(this._audio)
>      this._gain = this._context.createGain()
> ```

**Comment by chme** [comment]
Thanks for testing! Good to hear it is working now. I'll see if i can test Safari on MacOS tonight.

**Comment by chme** [comment]
Did not get the chance to test with Safari on MacOS. I hope it works and if not, that someone will report it before the next release :-)

**Comment by Porco-Rosso** [comment]
@chme Just tested it with Safari on MacOS, and it works flawlessly! Thank you!

**Pull request merged**
