### PR TITLE
support RSS streams (v2)

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Rework of https://github.com/ejurgensen/forked-daapd/pull/900, implementing https://github.com/ejurgensen/forked-daapd/issues/880

I've reworked this based on the comments you gave.  It's using `libmxml` for parsing the RSS/xml and retreived by `http_client_request`.  It's difficult to break this down further since the largest chunk of it is in the `rss` handling work (~830 of the ~1100 line changes)

* RSS feeds
Supports standard rss podcast feeds and also apple podcast feeds that we transform back to the normal rss urls.  To add/subscribe a feed:
```
curl -X POST "http://localhost:3689/api/library/podcast?name=bbcr4&url=https://podcasts.files.bbci.co.uk/p02pc9pj.rss"
```
To remove:
```
curl -X DELETE "http://localhost:3689/api/library/podcast?url=https://podcasts.files.bbci.co.uk/p02pc9pj.rss"
```
* DB
RSS feeds are treated like playlists and as such treated like a playlist in the db.
We have new media_kind `PL_RSS`.  We use the `playlist.path` fld to carry the feed URL.

* modules
Added `rss` scanner to library module and an abstract `register_events()` to allow modules to register their events on the library's eventbase.
`library` is the entry point for with `library_rss_save/remove()`.
The refresh is based on a set of rows from the db's `playlist` based on `PL_RSS` - each feed is given to  `rss_refresh_feed()`.
The `rss` lib module deals with retreiving the XML/RSS info and parsing before calling back to `library_playlist_save()` (for new feeds) and `library_media_save()`.
The library module doesnt provide queue_save or queue_add as different to a playlist.

* scans/purges
The `rescan()` and `initscan()` all call for a refresh of rss.  `metarescan()` does not do anything other than db ping the RSS feeds since.  This means that a user can force a RSS feed refresh at the start of the server by enabling an init scan or they can wait for the timer to kick and refresh.  A `fullscan()` is a little more tricky since theres no files on the filesystem to re-insert the feeds after they've been purged - this is where we have to take the RSS feeds from `playlist` into a tmp tbl, purge/drop all other records and then bring the records back into `playlist`.  I could update `db_purge_all()` to include th non-library RSS items but this goes against the "purge all" intent.

* artwork is not available
~We can't download the artwork even if available for the rss feed since we can't put it anywhere on the file system for the artwork subsystem to find.  we have to rely on embedded artwork to be used but this isnt always available~ Artwork on web i/f and IOS available with this patch https://github.com/ejurgensen/forked-daapd/issues/904#issuecomment-589328428 for artwork-embedded files, but does not use the image.url on the RSS feed 

* IOS remote app
The podcasts are seen and ordred correct (by release date) but relies on extending the fudge here:
```
--- a/src/httpd_daap.c
+++ b/src/httpd_daap.c
@@ -481,7 +481,7 @@ user_agent_filter(struct query_params *qp, struct httpd_request *hreq)
       // contained extended_media_kind:1, which characterise the queries we want
       // to filter. TODO: Not a really nice way of doing this, but best I could
       // think of.
-      if (!qp->filter || !strstr(qp->filter, "f.media_kind"))
+      if (!qp->filter || !strstr(qp->filter, "f.media_kind") || (qp->filter && strstr(qp->filter, "f.media_kind = 4")))
        return;
```
You'll have to excuse the commits - can squash on merge.
Thanks

### CODE REVIEW

**Comment by ejurgensen** [comment]
I can't offer continuously reviewing this PR, and as I mentioned before it would have been nice if you had made the PR and then continued working in another branch.

To me it looks like this PR is still a fair way from being acceptable. In particular, I don't like how rss is being added to generic modules like db and library. I also don't think there should be any need for a src/rss.c/h, nor a rss log domain, as I consider it a library module. I think it is important that you keep rss-specific stuff isolated in a library module, and thus keep the general parts general.

I will close this PR, but if you can make a new one that is final and is in line with the above principles, you are welcome.

**Comment by whatdoineed2do** [comment]
Can you help clarify these 2 as I these are confusing me:  When you say, can you clarify: 

"don't think there should be any need for a src/rss.c/h"
"rss-specific stuff isolated in a library module"

This is what `rss.c` tries to be - its localising all functions related to actually fetching and initiating the work to add RSS feed updates back to the library by calling newly added `library_rss_*()` functions.

I modelled the structure on `spotify_webapi` which also lives in the `src/` dir - I thought this was a `library` module - can you point me at one of the files that is so I can fit into the scheme you describe and i'll refactor.

The code and functionality is working as intended.

**Comment by ejurgensen** [comment]
Yes, I can understand your confusion. What I mean is that rss.c should be in the library directory, not in /src. spotify_webapi should probably also one day move to /src/library. It is where it is because it came before the library, and I also think it has or had some non-library functionality.

**Comment by whatdoineed2do** [comment]
@ejurgensen The refactor is almost done to what I think you're looking for but one more Q.

We are adding rss via the json.
```
httpd_jsonapi.c     jsonapi_reply_library_podcast_create()
                      url = evhttp_find_header(.., "url");
library.c             -> library_rss_save(name, url, limit)
library/rsscanner.c     -> scan_rss(..., url, ...)
                            http_client_request()  // get the xml pointed at by RSS URL
                            mxml extract of relevant flds
                            scan_metadata_stream()
                            // fill in mfi
                            library_media_save(&mfi)
```
This is a user input driven with user data (the RSS feed URL).  The existing updates/scans don't need input and thus fit into the abstract `library_source` `.scan`, `.rescan` etc.  But this is different.

How do you suggest exposing the `rssscanner`'s `scan_rss()` other than explicitly?

**Comment by ejurgensen** [comment]
Maybe one way of understanding what I am asking is this: As a thought experiment, let’s pretend that the rails you are building must also support that the user adds a Youtube video. Then I think it will be clear to you that stuff like jsonapi_reply_library_podcast_create() and library_rss_save() is no good. Instead, the general flow that applies to any media would be something like this:

1.	User picks some sort of “add to library” in the UI and adds a link to the media.
2.	This triggers a call to the JSON api with “json_library_add”, which passes it to the library abstraction, again just with “library_add”. Note that so far what is being added is opaque to json and the library. It just knows that the user wanted to add something.
3.	The library then determines which module should take care of this request, and it calls the function that the module has registered for scanning new items. Right now, modules can’t register such a thing, so that would probably need to be added. It would be a bit like “queue_item_add”, except here it is “library_item_add”. So a youtube module would set .library_item_add = youtube_scan.
4.	Now the module scans the item, and uses library_media_save and library_playlist_save to save whatever it finds. Again, there must be no library_rss_save, because the actual type of the item(s) is in the mfi/pli. There should probably also be a library_playlistitem_save, but currently playlist scanners just call db_pl_add_item directly.

The module must also be able to handle the various .scan calls. Here it must be able to identify the items in the library that it has previously added, so that they can be rescanned. For items in files I’m thinking data_kind is probably the easiest way of doing that, and it is what Spotify uses. For playlists I’m not sure what the best way would be, I don’t recall what the spotify module does.

**Comment by whatdoineed2do** [comment]
Thanks .. this is very valuable.  Let me work with this.  So in each `library_item_add` function, this would be responsible to determine if that type of url/item is for it to process and if so, it'd handle it, if not return `-1`

The various `.scan` functions work as you describe - since theres nothing on the filesystem, the (essentially) rescan functions find what RSS feed urls exists with the `PL_RSS` tag.

There is one final complication with `db_purge_all()` - with the RSS (and youtube) items being links and no db items, we would lose these in the `fullscan()` since it drops everything and looks again at the filesystem.  I was looking to get around this by preserving the non-library (RSS) items based on `path` starting `http` and saving these into a temp table and then restoring these after the `db_purge_all()`.  Is this workable?

**Comment by ejurgensen** [comment]
>  So in each library_item_add function, this would be responsible to determine if that type of url/item is for it to process and if so, it'd handle it, if not return -1

Yes, seems that is the approach for queue_item_add. The return value on "not on me" seems to be LIBRARY_PATH_INVALID.

> I was looking to get around this by preserving the non-library (RSS) items based on path starting http and saving these into a temp table and then restoring these after the db_purge_all()

You shouldn't need to do that. The library already has the ability to have items that are not in the filesystem, e.g. http streams and Spotify. The scanner should check that the item is still valid, and then ping it (update the timestamp). That will protect the item from the purge.

**Comment by whatdoineed2do** [comment]
> You shouldn't need to do that. The library already has the ability to have items that are not in the filesystem, e.g. http streams and Spotify. The scanner should check that the item is still valid, and then ping it (update the timestamp). That will protect the item from the purge.

All scans (update, meta, init) are ok with this and protected by the `ping`.  However its the `fullrescan() -> db_purge_all()` that doesnt `ping` anything to protect.  The `db_purge_all()` does an explicit:
```
"DELETE FROM inotify;",
"DELETE FROM playlistitems;",
"DELETE FROM files;",
"DELETE FROM groups;", 
"DELETE FROM playlists WHERE type <> PL_SPECIAL;"
"DELETE FROM directories WHERE id >="
```
It's the 4th statement that would be a problem for non-library RSS since this is the only location for the RSS url.  The other alternative is to extend the exclusion clause for the playlist delete.
```
sqlite> select id,title,type,media_kind,path,virtual_path from playlists;
id|title|type|media_kind|path|virtual_path
1|Library|0|1||
2|Music|0|1||
3|Movies|0|1||
4|TV Shows|0|1||
5|Podcasts|0|1||
6|Audiobooks|0|1||
14|bbcr4|4|1|https://podcasts.files.bbci.co.uk/p02pc9pj.rss|/https://podcasts.files.bbci.co.uk/p02pc9pj.rss
24|local|4|1|http://localhost/rss|/http://localhost/rss
```
We could agree/change the contract that a `fullscan` will only re-instate library items and this problem goes away.   For spotify, this may be ok as if you ahve a spotfy account it'll go and pull the non-lib content from your user account.  But for RSS, this isn;t the case as there's only the master copy of RSS url except in the `playlist` tbl.

**Comment by ejurgensen** [comment]
Yes, I didn't think about full_rescan, you are right that will indeed delete everything. Using the directories table to persist stuff sounds dirty to me. Since full_rescan is sort of "reset" I think it would be ok to just drop the items. I can't think of anything better.

**Pull request closed without merging**
