### PR TITLE
Use relative paths in web interface

### PR DESCRIPTION
**Pull request by mill1000**
This PR updates the web interface to use relative paths instead of absolute paths. This allows the web interface to be relocated and/or reverse proxied. e.g. you can configure an HTTP server running on port 80 to alias `hostname/forked-daapd/` to `hostname:3689`.

I believe I've found all the important references although I do not have the ability to test all the operations.

### CODE REVIEW

**Comment by mill1000** [comment]
Merged master to resolve conflicts

**Comment by chme** [comment]
Sorry for ignoring this PR for so long ... I'll include the changes in the next web interface update #1082

I think this change might also fix #1025

**Comment by mill1000** [comment]
Cool. No rush. If you need me to update this PR to fix merge conflicts let me know.

**Comment by chme** [comment]
Thanks, but it is not necessary. I have rebased your commit and included it in #1082

**Pull request closed without merging**
