### PR TITLE
Add a web api and a webinterface

### PR DESCRIPTION
**Pull request by chme**
I think it is time to add a proper web interface to forked-daapd ... and a web api ...

This is an early work-in-progress, it adds a json-api to forked-daapd and a web interface that makes use of it.

The json api has three endpoints:

- /api/library: returns an object containing information about the
library (number of artists, albums, songs) and the status if a rescan is
in progress

```
{
  "artists": 84,
  "albums": 151,
  "songs": 3085,
  "db_playtime": 687824,
  "updating": false
}
```

- /api/update: triggers a rescan of the library (returns an empty response)

- /api/spotify: returns an object with the information if spotify is
enabled and if it is the oauth uri to authorize access to the spotify
web api

```
{
  "enabled": true,
  "oauth_uri": "https://accounts.spotify.com/authorize/?client_id=...
}
```

The web interface makes use of these endpoints. It is reachable under "http://forked-daapd.local:[port]/admin.html"

It uses
- Vue.js: javascript framework
- axios: javascript library for ajax requests
- Spectre.css: CSS framework
- Elusive icons: icons

Perfect candidates for a (admin) web interface are the things, that are currently done via creating local files (pairing remotes, starting library rescan, logging into libspotify). Offering a web api endpoint for these would be the first step. 

@ejurgensen What are your thoughts on integrating a web interface into forked-daapd?

Screenshot:

screenshot from 2017-07-22 09 53 58

### CODE REVIEW

**Comment by ejurgensen** [comment]
I'm very excited about this! I agree it is high time, and it is thing that will benefit forked-daapd a lot by making it more accessible for ordinary users. I did try doing it myself once, but I got stuck. I also had trouble finding a web template/framework that looked nice but wasn't too intricate (i.e. too difficult for me to maintain). It is important for me that it looks good (clean), and I think the screenshot you provided looks promising.

I also think the way you have chosen to implement it looks very good. And yes, it makes sense to start with the endpoints you have focused on.

After that it would be good if the interface could show the current config.

An interesting problem after that will be what to do about config modification through the web api. I'm not sure what a good solution for that would be. I think making every option configurable at runtime will be a huge undertaking, and I'm also not sure it would even be a good idea. I'm thinking that probably web config needs to be implemented and considered on a per-option basis.

**Comment by chme** [comment]
evbuffer_add_file does not work on my raspberry pi. It gives following error `evbuffer_add_file: mmap(91, 0, 0) failed: Invalid argument`

I guess the third argument is the problem, as it probably states the number of bytes to mmap. Setting EVBUFFER_FLAG_DRAINS_TO_FD (http://www.wangafu.net/~nickm/libevent-2.0/doxygen/html/buffer_8h.html#a5db7e9063755accc56fdad87d662743e) on the evbuffer, gives no error but the number of bytes returned (and added to the evbuffer) is zero. Not sure what the cause is ... 

With the workaround in https://github.com/chme/forked-daapd/commit/c6e0535ffa2200c8679700d76b3fa324fe74a96f it works. 

Would be great, if you could test with and without this workaround, and check if the problem also occurs on your setup.

> I had trouble finding a web template/framework that looked nice but wasn't too intricate

I am not a web developer, so choosing a framework was not easy for me as well. For css, bootstrap is probably the most used framework. But the out-of-the-box look, is imho not that great. Spectre looked nice and it was not hard to use/understand.  

Regarding the javascript framework, there is a learning curve. Vue.js advertises itself as being "incrementally adoptable". Other candidates are react or angular, i looked briefly into them, but decided to try vue (they have a (probably biased) comparison with other js-frameworks on their website). 

> After that it would be good if the interface could show the current config.
>
> An interesting problem after that will be what to do about config modification through the web api. 

Yes, it would be nice to change config values through the web api. Moving config values to the db, would also have the benefit, that they could be migrated during version updates (instead of the config file conflict). But as you said, this will require more work.

In order to inform the web interface about status changes (e. g. library update finishes), we need to use websockets. libevent does not have built in support. That's why i am looking into https://github.com/warmcat/libwebsockets, if you know something better, let me know.

**Comment by ejurgensen** [comment]
> Would be great, if you could test with and without this workaround, and check if the problem also occurs on your setup.

Haven't tested this yet, but I do remember seeing this exact problem. Both when I messed around with a web interface previously, and also in connection with artwork.c, where you can see artwork_read() does not use it even though it would seem like the right function for exactly that.

I am impressed you found a fix, I never did that. Just worked around it...

About frameworks, I looked [at these](https://www.webpagefx.com/blog/web-design/small-css-frameworks/), mainly the one called Picnic.

I don't know better alternatives for websockets, my only thought is that I think the libevent folks were planning on transitioning the http stuff to some other library, which might have websockets? Can't remember the name of it, and Google couldn't help me here.

**Comment by chme** [comment]
> I am impressed you found a fix, I never did that. Just worked around it...

Well, i did not found a fix, just the same workaround you made. I have libevent in version 2.0.22 on my dev system (debian and ubuntu have 2.0.21). My hope is that the issue with evbuffer_add_file was fixed, but i did not verify it.

> I don't know better alternatives for websockets, my only thought is that I think the libevent folks were planning on transitioning the http stuff to some other library, which might have websockets?

I think you mean libevhtp. But the integration seems to be at best on hold (https://github.com/libevent/libevent/issues/261).
The libwebsockets library has a libevent integration with current stable version 2.3. It allows to use a libevent loop with libwebsockets. This would be really nice, currently i am using a separate thread for the websocket, which could be spared if it could be easily integrated in the existing httpd thread.

Debian (stretch) and ubuntu (17.04) have libwebsocket 2.0.3 in there repositories. Locally i tested with 2.0.2 and current master. Compiling against the versions in jessie fails (version 1.2.2), therefor at least 2.0.2 is required. The websockets are not vital for the web interface, but increases usability in my opinion significantly. 

I switched from spectre to builma, which seems to be more feature complete. 
Besides updating the library there is now support for pairing remotes.


This is what it looks now:
image


And on a small screen:
image

**Comment by ejurgensen** [comment]
Man it looks awesome, can't wait to test it. Will probably be in a week or so. Let me know when it is ready for merging.

**Comment by roblan** [comment]
Just a thought - maybe separate web interface (vue app) from forked-daapd?
It would be easier and faster to implement changes that way.

**Comment by chme** [comment]
@roblan One goal of this pr is definitely to enable building web interfaces independently from forked-daapd. But currently that is not possible due to the missing json api (there are ways to build a web interface with the existing protocols, but this is in my opinion quite cumbersome). 

I believe it is best to offer a web interface out of the box and as long as @ejurgensen agrees, this should be developed as part of forked-daapd. 

@ejurgensen I am working on integrating the libspotify login into the web interface. I hope to have it ready to review/merge in a week.

**Comment by roblan** [comment]
@chme JSON API is one thing and it is needed to create such interface for sure.
But webapp in the other hand is a whole new separate app (which, hopefully, will grow over time, and will need its own build process, etc.) and deserves its own repo IMO.

But that's only mine 2 cents ;)

**Comment by ejurgensen** [comment]
I agree with @chme, I think it will be easier for most users if it just there out of the box. I think the web interface will mean a lot for forked-daapd, because it will make it much more accessible.

**Comment by chme** [comment]
I think this is now good for a first review/test. Unfortunately GitHub does not show the commits in the correct order (probably due to rebasing/squashing).

Some notable changes that should be reviewed:

1. The JSON api uses the same authentication (user/password) as the admin web interface
2. Therefor i removed the default password (without password the web interface is only reachable from localhost but not from a remote client).
3. The JSON api requires `libjson-c-dev`, i think this needs to be reflected in configure as it is not an optional dependency anymore
4. forked-daapd now notifies clients about remote pairing, library update and Spotify status changes

What is still missing / some questions:
* Documentation changes (readme, install and probably a new readme for the JSON api)
* Should the JSON api get its own log domain?
* travis-ci does not build with --enable-websocket as it is based on ubuntu 14.04 with a heavily outdated libwebsockets library. This could be solved by using docker based builds.
* Building with websockets is an opt-in (--enable), should it be opt-out (--disable). I think the later would be better as the best experience is with websockets enabled.
* The current Spotify OAuth is still in place, should it be removed?
* The admin web interface is only reachable under http://forked-daapd.local:port/admin.html. Should it also be reachable under http://forked-daapd.local:port/ ?

**Comment by ejurgensen** [comment]
I'll review it asap! On your questions:

> Documentation changes (readme, install and probably a new readme for the JSON api)

Yes, there will be the challenge that there will need to be two different sets of documentation: One matching the versions that are out there in the distros now, and a significantly revised version that fits with the web interface. Maybe a way to do it would be to have link up in the top of the revised README (which is the basis of http://ejurgensen.github.io/forked-daapd/) pointing to the old docs.

> Should the JSON api get its own log domain?

Don't really have an opinion on that :-)

> Building with websockets is an opt-in (--enable), should it be opt-out (--disable). I think the later would be better as the best experience is with websockets enabled.

I agree

> The current Spotify OAuth is still in place, should it be removed?

Yes, I would say so

> The admin web interface is only reachable under http://forked-daapd.local:port/admin.html. Should it also be reachable under http://forked-daapd.local:port/ ?

Yes, I think that would make good sense

**Comment by ejurgensen** [comment]
I'm a bit short on time, so I haven't been able to deep dive in the changes, but here is a bit of feed back from my testing:

1. The "Update library" suggests to the user to click to update, but I'm afraid that will give the user the impression that that is always required. I think it would be good to say something like "Your library is automatically monitored for changes by forked-daapd, but if changes are not being detected, you can scan for them."
2. Should "Update library" have options for both a full rescan and init rescan?
3. If websockets are disabled, then after initiating the pairing you have to browser refresh manually (F5) to get the pairing prompt. Would be better to have a button for that, I would say.
4. Are you planning to also add support for device verification and LastFM? I hope so :-)
5. On my iPhone the title bar was somewhat cluttered, see below.
6. Should web_root_path be configurable? I don't really think so.
7. I'm in favor of not having any auth on the interface by default. I mean, daap, dacp and mpd are already open. Of course people should be able to set a password, if they want.
8. The "websocket_port" is a difficult option. Does it need to be there?
9. httpd.c line 1100: non-adjusted copy/paste from artwork
10. I don't like to maintain build options both in main.c and in src/httpd_jsonapi.c. I think it should be unified, and the maintainence should not be in src/httpd_jsonapi.c.
11. src/listener.h line 19: typo
12. logger: Maybe websockets and the admin interface could share a log domain?
13. Good idea to put json routines in a common misc-file
14. (didn't get to look at the spotify changes)

img_1966

**Comment by chme** [comment]
Thanks for taking the time to look into this! 

> Should "Update library" have options for both a full rescan and init rescan?

I would only expose the init rescan. The full rescan deletes play count info and takes ages to finish ... and i am not sure if it is well tested (i never use it and the readme states it should only be used for troubleshooting).

> Are you planning to also add support for device verification and LastFM? I hope so :-)

Yes, i started implementing support for device verification (i will not be able to test this) and LastFM. It turns out the current web design does not scale well with a lot of cards. It simply takes too much space. I am thinking about an alternative layout.

> Should web_root_path be configurable? I don't really think so.

Well, it makes it easier to develop the web interface. I am pointing it to my workspace and therefor can omit the "make install" part. It is also a (crude) way to replace the default web interface with another one. But i have no strong feelings and can remove it.

> I'm in favor of not having any auth on the interface by default. I mean, daap, dacp and mpd are already open. Of course people should be able to set a password, if they want.

I would keep the limitation, that without a password access is only granted for localhost. Hopefully at some point, it will be possible to change some of the configuration through the web interface. And this should only be possible for authorized users.

> The "websocket_port" is a difficult option. Does it need to be there?

It is not possible to use libevent for http requests and libwebsockets for websocket requests on the same port. It would be possible to use libwebsockets for http and websockets on the same port. But this also requires a configurable port.
I will set a default port number, but i don't see how this one is more complicated than the existing port configurations. 

> logger: Maybe websockets and the admin interface could share a log domain?

Yes, that makes sense. Something like L_WEBAPI?

**Comment by ejurgensen** [comment]
Yes, I also never use full rescan, and it is fine to omit it. Hope it works, though :-) If someone needs we can add later. Maybe call it something like "Purge and rescan" when we do.

I would prefer if web_root_path was not configurable.

Good if you can set a default value for the websocket port. With no default the configuration would have been difficult to understand for most people. I agree that it is good to have the port configurable like the others.

Maybe L_ADMIN or L_WEB instead of L_WEBAPI? For the end user it is not so much an api.

**Comment by ejurgensen** [comment]
Just wanted to hear: Do you think I should merge now, or do you have more commits around the corner?

**Comment by chme** [comment]
Sorry, i did not found much time to work on this pr. I still need to address some of the issues you found. 

Before this is ready to merge, i think the following issues should be fixed:

[ ] Button to check for pending remote pairing (and device verification), if websockets are not enabled
[ ] Default port for websocket
[ ] Change build option to include websockets by default
[ ] Change configure to always check for libjson-c
[ ] Change logdomain L_WS to L_WEB and use it also in httpd_json.c
[ ] Remove config option for web_root_path

This one would also be good to address before merge (?):

[ ] Adjust README and INSTALL

And these would be nice to have, but can also be done in a follow up pr:

[ ] Revisit webdesign (the approach with cards does not scale well)
[ ] Integrate device verification
[ ] Integrate LastFM login (and logout)
[ ] Integrate Spotify logout


Regarding the documentation challenges, i like how mopidy documents their different versions. They are using https://readthedocs.org/. With readthedocs it is easy to select the documentation for the right version.

**Comment by ejurgensen** [comment]
I see you pushed some commits - so perhaps ready to merge now? We can do the README later (or readthedocs).

**Comment by chme** [comment]
Yes, I think it is good to be merged. I didn't have the time to add device verification and last.fm support. So this too needs to be done later.

**Comment by ejurgensen** [comment]
Alright, merged. Once again, fantastic work, this a huge step forward!

**Comment by ejurgensen** [comment]
Added a few changes to this, one was a missing include, the other was that I changed it so websockets get enabled/disabled based on the check of whether the library is present. This is to avoid configure bailing on relatively new Ubuntu releases, even when libwebsockets is present, but just not >=2.0.2.

I also noticed that I get compile warnings about unused variables. Will you get those cleaned up?

**Comment by chme** [comment]
My compiler only complains about missing variables in the ANTLR generated code (which are there for ages and probably need fixing in ANTLR). Can you point me to the other unused variables (and maybe your configure statement)?

**Comment by ejurgensen** [comment]
Here are the unused vars (looks like they come when building without Spotify?):

```
httpd.c: In function ‘oauth_interface’:
httpd.c:220:7: warning: unused variable ‘ret’ [-Wunused-variable]
   int ret;
       ^
httpd.c:219:9: warning: unused variable ‘errmsg’ [-Wunused-variable]
   char *errmsg;
         ^
httpd.c:217:15: warning: unused variable ‘ptr’ [-Wunused-variable]
   const char *ptr;
               ^
httpd.c:216:15: warning: unused variable ‘req_uri’ [-Wunused-variable]
   const char *req_uri;
               ^
httpd.c:215:20: warning: unused variable ‘query’ [-Wunused-variable]
   struct evkeyvalq query;
                    ^
httpd.c: In function ‘httpd_init’:
httpd.c:1653:2: warning: label ‘websocket_fail’ defined but not used [-Wunused-label]
  websocket_fail:

httpd_jsonapi.c: In function ‘jsonapi_reply_spotify’:
httpd_jsonapi.c:203:9: warning: unused variable ‘oauth_uri’ [-Wunused-variable]
   char *oauth_uri;
         ^
httpd_jsonapi.c:201:7: warning: unused variable ‘httpd_port’ [-Wunused-variable]
   int httpd_port;
       ^
httpd_jsonapi.c: In function ‘jsonapi_reply_spotify_login’:
httpd_jsonapi.c:260:7: warning: unused variable ‘ret’ [-Wunused-variable]
   int ret;
       ^
httpd_jsonapi.c:259:16: warning: unused variable ‘errors’ [-Wunused-variable]
   json_object* errors;
                ^
httpd_jsonapi.c:258:16: warning: unused variable ‘reply’ [-Wunused-variable]
   json_object* reply;
                ^
httpd_jsonapi.c:257:9: warning: unused variable ‘errmsg’ [-Wunused-variable]
   char *errmsg = NULL;
         ^
httpd_jsonapi.c:256:15: warning: unused variable ‘password’ [-Wunused-variable]
   const char *password;
               ^
httpd_jsonapi.c:255:15: warning: unused variable ‘user’ [-Wunused-variable]
   const char *user;
               ^
httpd_jsonapi.c:254:16: warning: unused variable ‘request’ [-Wunused-variable]
   json_object* request;
                ^
httpd_jsonapi.c:253:20: warning: unused variable ‘in_evbuf’ [-Wunused-variable]
   struct evbuffer *in_evbuf;
                    ^

```

**Pull request merged**
