### PR TITLE
Merge forked-daapd-web into forked-daapd

### PR DESCRIPTION
**Pull request by chme**
Include player web interface source files from https://github.com/chme/forked-daapd-web into forked-daapd (the new `web-src` folder).

To better separate the admin from the (prebuild) player web interface, this pr also restructures the `htdocs` folder. The prebuild player web interface consists of:
- `htdocs/index.html`
- all files under `htdocs/player`

The rest of the files belong to the admin web interface. Libraries used by the admin web interface are located in the `htdocs/admin/vendor` folder.

I only did a really short test, so this definitely needs more testing.

@ejurgensen i would appreciate, if you can take a closer look at the changes to Makefile, INSTALL and the READMEs.

@rbalint fyi

### CODE REVIEW

**Comment by chme** [comment]
@whatdoineed2do No need to close the existing prs against forked-daapd-web. I'll try to look at them soon. But i will probably not merge them into forked-daapd-web and instead you will have to resubmit them against forked-daapd (once this pr is merged).

**Comment by chme** [comment]
@rbalint it would be nice, if you could take a look at this.

I am not sure, if it is possible to include the admin web interface in the debian package. The admin web interface does require `bulma`, `fontawesome`, `vue` and `axios`. But we do not build and minify the required js, css files. 

Is this acceptable in debian packages?

If it is not, @ejurgensen and i where discussing, if the admin web interface could still be included without the required libraries and `admin.html` could be patched to load the libraries like bulma and vue from a CDN. That would allow to remove them from the `htdocs/admin/vendor` folder.

The patch for `admin.html` would look like:

```
diff --git a/htdocs/admin.html b/htdocs/admin.html
index dcc08b0..8bc3372 100644
--- a/htdocs/admin.html
+++ b/htdocs/admin.html
@@ -6,12 +6,12 @@
   <title>forked-daapd</title>
   
   <!-- Hosted libraries -->
-  <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"> -->
-  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css"> -->
+  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
+  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
 
   <!-- Local libraries -->
-  <link rel="stylesheet" href="/admin/vendor/fontawesome/css/all.min.css">
-  <link rel="stylesheet" href="/admin/vendor/bulma/bulma.min.css">
+  <!-- <link rel="stylesheet" href="/admin/vendor/fontawesome/css/all.min.css"> -->
+  <!-- <link rel="stylesheet" href="/admin/vendor/bulma/bulma.min.css"> -->
 
   <link rel="stylesheet" href="/admin/css/forked-daapd.css">
 </head>
@@ -275,12 +275,12 @@
 </div> <!-- #root -->
 
 <!-- Hosted libraries -->
-<!-- <script src="https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.min.js"></script> -->
-<!-- <script src="https://unpkg.com/axios@0.18.0/dist/axios.min.js"></script> -->
+<script src="https://cdn.jsdelivr.net/npm/vue@2.5.17/dist/vue.min.js"></script>
+<script src="https://unpkg.com/axios@0.18.0/dist/axios.min.js"></script>
 
 <!-- Local libraries -->
-<script src="/admin/vendor/vue/vue.min.js"></script>
-<script src="/admin/vendor/axios/axios.min.js"></script>
+<!-- <script src="/admin/vendor/vue/vue.min.js"></script> -->
+<!-- <script src="/admin/vendor/axios/axios.min.js"></script> -->
 <script src="/admin/js/forked-daapd.js"></script>
 
 </body>
```

I would appreciate, if you could share your thoughts on this.

**Comment by chme** [comment]
@Porco-Rosso Yes, this will mean an internet connection is required to access the admin web interface. I would prefer, if the libraries could be part of the package, but if not, i think having the admin webinterface with this restriction is better than having none.

**Comment by chme** [comment]
@ejurgensen if you have no objections or noticed something that should be adjusted regarding the documentation, can we merge this? It should at least be an improvement. The source of the web interface will be part of the forked-daapd source tree and there are instructions on how to compile the javascript/css/html files.

**Comment by ejurgensen** [comment]
Merged now, thanks a million for this contribution.

@rbalint I hope you have a chance to consider the suggestions made by @chme above regarding Debian packaging.

**Comment by rbalint** [comment]
@ejurgensen @chme Thanks for merging the web interface. I'm packaging 26.4 and collect what depencies are missing from Debian to build the interface there. Pulling the missing pieces is considered a privacy breach https://lintian.debian.org/tags/privacy-breach-generic.html thus I can't ship forked-daapd doing that by default, but shipping configuration files to let users enable the external pieces is not directly prohibited by the Policy and I'm looking into that option.

**Pull request merged**
