### PR TITLE
configurable options to show composer on web `Now Playing` page

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Closes https://github.com/ejurgensen/forked-daapd/issues/631

Composer was exposed on jsonapi in commit cfadcc184faa9fc19ecebca43adaceba33fe0ef4.  This PR has server side configuration to determine which genres the `Now Playing` should attempt to display.

before-after
Composer is displayed under title (in non bold) on the screenshot on the right.

@chme previously had reservations about hardcoding logic (in websrc code) to display when `genre == classical` - this PR allows user/server config to determine list of `genres`that the user wants to display composer.

### CODE REVIEW

**Comment by LordMyschkin** [comment]
May I just ask politely - I am sure there are conditions I do not understand - why displaying the composer just when the "composer"-Tag is set is a bad idea?

**Comment by whatdoineed2do** [comment]
I recall @chme mentioning that some folks add a tag composer to their files which isn’t just for genres like “classical” or “soundtrack” etc.  In those situations showing the composer on the now playing page may not be desirable esp if it’s hard coded in the web if js.

People like myself, who are less complete with my metadata, only add composer to my classical files so hard coding the check I used before was not an issue. But it would be for others.

I know composer is added on the track info modal dialgue but I think we can do better with it be on the now playing page and hope the guys agree with the approach

**Comment by chme** [comment]
Sorry for taking so long to respond. I am fine with making this a configuration option. But i would like to keep it simple. I think most users want to either display the composer or not. Therefor a simple boolean config option should be enough (default should be `false`). 

The new config option should also be included in `forked-daapd.conf.in` (with a short description).

**Comment by whatdoineed2do** [comment]
updated the PR - for some reason the `conf.in` file got missed in the commits.

I think we should give the end user the flexibility to specify which genres they care about as well as the simple binary display/not display case.  This in the PR where the config file's `show_composer` variable can take:
* an empty list (default) which disables the display of composers: `show_composer = { }`
* a list that contains `"*"` which enables display composers if present: `show_composer = { "*" }`
* a comma separated list of case insensitive genres to display genre: `show_composer = { "classical", "soundtrack", ...}`

As part of another PR (showing compilation albums) I've been putting some of my library through MusicBrainz which is tagging composers for every file.  I'd only want to display composer for classic and soundtracks and not for others (such as Pop, Rock ... that MB has also tagged).

**Comment by chme** [comment]
I am not thrilled by this solution. It is rather complex and it is not clear to me, that this really solves an issue. The problem with configurable genres to show the composer is, that the user may need to adjust the config file and restart forked-daapd, if new music gets added that contains a genre that is not yet in the list (or the user needs to manually edit the genre tag).

I would be fine with a simple yes/no option. This allows users that manually manage the composer tag to show it on the now playing page. But guessing whether to show or hide the composer based on the genre is imo not a good solution.

How are other music players handling this?

**Comment by LordMyschkin** [comment]
Most players ignore the Composer Tag: Cantata (so sad support for windows ist discontinued), gmpdb (which is from 2011) and my preferred ympd do so.
I patched forked-daapd to always show the composer (or leave the line blank if there is none) on the now playing page (and the path) - works very good for me, I see no disadvantage, to be honest. But it may be disturbing for people with less classical music - although my guess is they would never notice because the Composer-Tag is just not set.

**Comment by whatdoineed2do** [comment]
I've not come across any other player that shows composer - looked again at itunes, Apple Remote app, volumio webui.

> not clear to me, that this really solves an issue. The problem with configurable genres to show the composer is, that the user may need to adjust the config 

The config setting is either dumb binary enable/disable or a list.  For the majority of users the _need_ to update the config for other genres is redundant as they just will never need to add any other genre's to the configuration option once set the true or false.  For folks (incl me) that care / only want composer for subset of genres this works and if they care enough to control this list  then update cfg/restart the process is low cost effort for the control.

Consider this:  are the files with `composer` tagged ONLY on the files that you care about?  or are they on other files?  For music files that have gone through MusicBrainz or another autotagger the meta is much fuller where all files are getting tagged with a composer.  Why enforce users to see a composer's name on a Pop track where they don't care.  In such autotagged files I'd care only to see composer for my  classical, soundtrack files.... or anything else they want to add to the list.  A true/false limitation would be no better than currently which doesn't show the composer.

As for complexity - its not much more complex than the binary yes/no.  This PR:
* json sends lowercase'd list over to webclient and webclient checks genre string is in list to determine show/not
vs
* json sends true/false over to weblickent and webclient checks bool to determine show/not
so I don't think there's anything of concern here.

**Pull request closed without merging**
