### PR TITLE
OSX patches

### PR DESCRIPTION
**Pull request by sshambar**
These patches include the missing high resolution timers and direct Bonjour support, and the necessary configuration changes needed to compile/run on OSX.  I've only done limited testing, but everything appears to work at first glance.  This is a branch off of fixthreads, so it includes all those changes too.

### CODE REVIEW

**Comment by sshambar** [comment]
Hold on merging this... the mdns browser still needs some fixing up (documentation is vague in places, so I'm analysing the apple source)

**Comment by sshambar** [comment]
Cleaned up the resolve code so it now keeps resolving until a timeout expires (rather than just getting first group of responses).  Fixed the network order on port number, so it now works too :)

**Comment by ejurgensen** [comment]
Had a look at this, looks good to me. Before merging I would like to know if you are ok with future fixing up of mdns_dnssd, if bugs show up or updates are required? I won't be able to do it.

**Comment by sshambar** [comment]
Yes, although I travel quite a bit, so at any point in time, I may be out of contact for sometimes weeks at a time.  Otherwise, sure!  I read much of Apple's mDNSResponder to figure out a few issues I was having, so I'm pretty familiar with it now :)

**Comment by ejurgensen** [comment]
Could you add some OSX installation instructions to the INSTALL file?

**Comment by sshambar** [comment]
I guess I could add a section discussing how to install the required macports packages... although homebrew probably would also work (I've just never used it).  Is that what you're thinking?

**Comment by ejurgensen** [comment]
Don't know much about OSX, so it's up to you which instructions to provide in the INSTALL.

**Comment by couteau** [comment]
I use Homebrew on my mac, and can add install instructions for that.

**Pull request merged**
