### PR TITLE
Support for shairport-meta artwork

### PR DESCRIPTION
**Pull request by stufisher**
Not sure if this is the best implementation of this, but it works. I have not spent a huge amount of time getting into the internals of forked-daapd. Relates to #456

### CODE REVIEW

**Comment by ejurgensen** [comment]
Indeed a simple solution that should work, but I still have to reject it. Using the filesystem to transfer data internally is a bit too rough for me, and it also breaks the principle that forked-daapd only needs read access to the library.

**Comment by stufisher** [comment]
Yes i'm aware writing to the file system is far from optimal. I do not have a lot of time to dedicate to this but I am open to other suggestions. 

From my brief read of the code this all looks to run asynchronously:
1. pipe receives metadata
2. sometime later artwork module ask for artwork
in which case at some point we'll need to store the binary somewhere

the other option i can see is to drop the image binary (base64 encoded?) into metadata->artwork_url, but the problem is that will then get dumped into an sqlite column. I've no idea if that column can handle in excess of a 70kb image (+30% for base64 encoding, i'd guess not). Then it would be possible to retrieve this from the db and decode this in a dedicate pipe artwork handler. 

Thoughts?

**Comment by ejurgensen** [comment]
I haven't taken a closer look at it, but it might be an option to store the artwork in a proper tmpfile (not in the library) and then pass a file:// url to the artwork module. Or maybe even better to use the cache as storage, perhaps using cache_artwork_stash().

However, if you haven't got so much time then it is probably best to leave it to someone who has.

**Comment by ejurgensen** [comment]
I've now added support for this (with commit 7316c060b8817ecd0f058d2788b3f6ad299a55f0)

**Pull request closed without merging**
