### PR TITLE
[jsonapi] Fix segfault if no default playlist directory is set in conf

### PR DESCRIPTION
**Pull request by chme**
Alternative for #750 
@ejurgensen if you have time, could you take a quick look? Will do some tests during the day and merge afterwards.

### CODE REVIEW

**Comment by ejurgensen** [comment]
The change looks fine to me. It seems that the two options are co-dependent (if understand correctly you cannot set one of them without also setting the other?), so you could merge them into one, the playlist dir setting. It might make things a bit simpler.

**Comment by chme** [comment]
Thanks for taking a look. I'll merge this as is, to fix the segfault.

The playlist modifying capabilities in the JSON API are currently limited. The mpd clients have more options and can modify (add tracks to an existing playlist, create or delete a playlist) in every directory that is part of the library, if "allow_modifying_stored_playlists" is set to true. The "default_playlist_directory" config is only used, if no absolute path is given for the playlist.

Do you think, it would be better to limit playlist modifications to the playlists in the configured directory?

**Comment by ejurgensen** [comment]
My point wasn't about the feature itself, more that it seems "allow_modifying_stored_playlists" isn't necessary as a config option.

As I read this commit, if the user enables "allow_modifying_stored_playlists" but doesn't set "default_playlist_directory", then "allow_modifying_stored_playlists" gets disabled. Conversely, setting default_xx, but not setting allow_xx has no effect.

So since setting just one of the options is equivalent to setting none of them, the same could be achieved by just having default_xx as a config option.

**Comment by chme** [comment]
That is only true for the current JSON API. For MPD clients setting "allow_modifying_stored_playlists" to true is enough. "default_playlist_directory" is not required. It makes sense to align the JSON API with the MPD clients, to avoid that confusion. My question is, if you have a preference to either generally restricting it to the configured directory or extending the JSON API to also allow modifying playlists outside the configured directory. For me both solutions are fine, if we choose the first, removing the boolean option makes sense.

**Comment by ejurgensen** [comment]
Ok, makes sense. I wasn’t aware of the mpd part, I had just read this PR. It sounds fine to be able to modify any playlist if enabled, I suppose it might be useful in some contexts.

**Pull request merged**
