### PR TITLE
Expand JSON/websocks interfaces to include more LISTENERS

### PR DESCRIPTION
**Pull request by ryanlath**
An expanded JSON api and websockets interface would allow for easier development of alternative remotes and whatnot.  I started with the LISTENERS I thought most useful.  

I add the "PLAYER" interface to the admin.html as a test case.

### CODE REVIEW

**Comment by chme** [comment]
Thanks! Nice to see there is interest in using the JSON api. I also started adding new endpoints to the JSON api. You can take a look at that in my branch: https://github.com/chme/forked-daapd/tree/web_remote (just to save duplicate work).
I opted to add a new "player.html" instead of extending the "admin.html". I hope to find some time this evening to look at your changes and how it compares to my wip changes.

**Comment by ryanlath** [comment]
Doh!  Lots of duplication already.  So, you can ignore my pull request.  

Is there a reason the JSON api/websockets from 'web_remote' stuff isn't in 'master'?  It doesn't seem to have any interaction with other parts of the program.  It would be easier to work on for me, and maybe for others, since it wasn't obvious work was being done on it.  

Also, have you thought about how you're going to name the rest of the API?  If you have, could you list some examples/thoughts.  Particularly, concerning browsing.  It would be helpful to me, since I'm currently using a mixture of JSON and daap/itunes calls and I'd rather move to all JSON.

```
       //  Like this, but for browsing :-)
	{ .regexp = "^/api/player/stop", .handler = jsonapi_reply_player_stop },
```

**Comment by chme** [comment]
@ryanlath I was not sure, if the changes to the json api would be helpful for others (and my work on a web interface to control playback is not ready to be merged). I have created pr #460 with my changes to the json api from the web_remote branch (plus the notification for queue events and the queue-version and queue-count information in the queue-endpoint).

I am not quite sure, how the browsing part of the api should look like.

Maybe something like:
```
/api/library/artists
/api/library/albums
/api/library/tracks
```

With support for query parameters:
```
/api/library/albums?artistid=123
/api/library/tracks?albumid=456
```

An alternative to show the albums of an artist would be something like: 
```
/api/library/artists/{id}/albums
```

And what is missing, is how to handle audiobooks and podcasts. So maybe it would make sense to do something like:

```
/api/library/music/artists
/api/library/music/albums
/api/library/music/tracks
/api/library/podcasts
/api/library/podcasts/tracks
/api/library/audiobooks
/api/library/audiobooks/tracks
```

Do you have a recommendation/preference?

**Comment by ejurgensen** [comment]
I have merged the pr from @chme, but I am actually not so thrilled about going in the direction of adding a built-in web player. I would prefer that the web interface was for admin stuff.

The thing about a web player is that it can easily become a pretty large project. First you've got start/stop, then more advanced playback control, then queues, then browsing, then artwork, then ratings and then probably a bunch of other stuff. It's an implementation of the entire daap/dacp combo, or mpd for that matter. And there are already a selection of mpd web interfaces out there, so won't it be like reinventing those?

**Pull request closed without merging**
