### PR TITLE
[mpd] Close connection for close command

### PR DESCRIPTION
**Pull request by wolfmanx**
@chme It is a bit annoying having to kill my telnet session manually and reset the terminal when debugging/testing.

### CODE REVIEW

**Comment by ejurgensen** [comment]
@chme is this ok?

**Comment by chme** [comment]
The change is ok. A comment would be nice, explaining, that freeing the bufferevent closes the connection.

**Comment by wolfmanx** [comment]
@chme I have commented it extensively, as it is non-obvious and took me quite some research to find it.

**Comment by chme** [comment]
Great, thank you!

**Comment by ejurgensen** [comment]
Merged, thanks!

**Pull request merged**
