### PR TITLE
Rework mpd command lsinfo 

### PR DESCRIPTION
**Pull request by chme**
Hi @ejurgensen,

this is my attempt at addressing the performance issue (and timeouts during import in MPod) for the mpd command 'lsinfo'. As briefly discussed i added a new table to store the directory informations and the files and playlist table both have a new column 'directory_id'. The directories table gets filled as part of the file scan and during the spotify updates. 

I did not (yet) dare to change/drop the existing inotify table, but this may still be an option. On the other hand it might be good to keep the inotify logic separated from the stored library. 

My first tests are promising, the import in MPod worked correctly were it previously failed. 

The first a commit separates the db upgrade logic into its own source file and is not directly related to the changes regarding the lsinfo command.

Would really appreciate your feedback on this.

### CODE REVIEW

**Comment by ejurgensen** [comment]
Hi chme, thanks for this pr, I think it looks very promising. I've collected some feedback below, but since I haven't worked in depth with this, some of it may be misguided. Anyway:

- Good to put the upgrade stuff outside of db.c
- The db_directory functions are not exclusively for directories. Maybe vpath would be better naming than "directory"? Or something else?
- What about sqlext.c? Are some of the functions previously introduced now obsolete?

More specific stuff:
filescanner_playlist.c 242: db_directory_addorupdate() would be repeated a lot - how about creating the base dirs (file, http, spotify) right away? Say in db_init?

filescanner.c 124: "enum root_directories" seems not to be used? Maybe it is for later?
filescanner.c 987: Am I missing something or is "struct directory_info di" not actually used?
filescanner.c 1008: The function already creates an error message, so maybe you can just return? (same goes for other places)
filescanner.c 1178: Necessary to copy? It is copied again by create_virtual_path. Since path is not const you can just put '\0' in it, or maybe use strtok?
filescanner.c 1189: I suggest you remove these kind of line breaks (same goes for other places)

spotify.c 624: In the snprintf() use sizeof() instead of PATH_MAX? Maybe the result also needs some error checking.
spotify.c 625: Especially the first db_directory_addorupdate() will result in a lot of superfluous queries? Suggest creating the base once with db_init.

Let me know when you think the pr is ready.

**Comment by chme** [comment]
Thank you for the review, I addressed most of your comments with the last commits. 

I am not sure what you mean with "The db_directory functions are not exclusively for directories.", the functions operate on the directories table, which contains only entries for directories.

> filescanner.c 1178: Necessary to copy? It is copied again by create_virtual_path. Since path is not const you can just put '\0' in it, or maybe use strtok?

There needs to be at least one copy operation because the path parameter should not be changed (it is used after calling the function). It is possible to only copy once and then operate on the same string, but i do not think this will improve the code readability. 
Calling the process_parent_directories function is probably only necessary for a bulk scan (only for the library path). I am looking into removing the call from the inotify functions (the parent directory should already exist and a select to retrieve the id should be enough).

I moved the creation of the  directory entries for the base folders "/file:", "/http:", "/spotify:" into the db init as you suggested. It avoids unnecessary select/updates and simplifies the code a bit. The only downside is, that they are currently always visible even if there are no spotify songs or http streams in the library.

**Comment by ejurgensen** [comment]
Sounds good.

I was thinking if it might be option to not add each subdir separately? So if my music is in /a/b/c/Music, then you would just have one entry in the directory table for the entire path? As I understand, the reason you need this in the first place is to support browsing, and I am thinking that users don’t really want to navigate all the way through a, b and c to get the actual folder? Or maybe this will break the way the mpd protocol works?

What I meant by "The db_directory functions are not exclusively for directories." is that for http: and spotify: they are not dealing with actual directories. So maybe the directory naming could misguide? Well, in any case, it is not terribly important for me.

**Comment by ejurgensen** [comment]
BTW since you will be doing a database upgrade could you then also add these two columns:

-	a “date_released” (int) to the files table (ref. https://www.raspberrypi.org/forums/viewtopic.php?p=882434#p882434)
-	a “name” (varchar) field to the speakers table (this will just make it a bit easier to debug)

**Comment by chme** [comment]
> I was thinking if it might be option to not add each subdir separately?
I was thinking about this too, but mpd clients offer to browse to the parent dir of a folder and therefor would try to access e.g. /a/b/c, which would then require special handling. I was thinking about giving each library path in the config file a name (either generated as local1, local2, ... or user defined). This would solve the browsing issue for parent folders.
But another problem is, if the user changes the library path in the config file from /a/b/c/Music to /a/b/c. The bulk scan than would not rescan the files/folders as they are unchanged, but it would be necessary to update the directory references. 

Because of that i sticked to create the parent folder structure in the directories table.

**Comment by chme** [comment]
The next round of changes ... 

I added some logic to prevent that the root directory for spotify shows up, if the user does not have a spotify account. This is done by disabling the root folder (the magic value 4294967296 is the one that gets stored in my sqlite3 db for the INOTIFY_FAKE_COOKIE value). It is enabled after successful login.

The previous changes must have broken the compile on freebsd. I tried to fix this, but it is totally untested (even the compile is not tested) as i do not have a running freebsd system. If someone has a running system and could try the changes, this would be great ...

I also added the additional columns you requested.

**Comment by chme** [comment]
Fixed the missing definition of the new column 'date_released' in media_file_info and db_media_file_info (squashed into  8600c21).

@ejurgensen please take another look

**Comment by ejurgensen** [comment]
I just tried building in FreeBSD, and it failed because get_parent_dir_id() is used in line 2058, but only defined for Linux.

**Comment by chme** [comment]
I moved the get_parent_dir_id() function and hope this solves the compile problem. I tried compiling forked-daapd on freebsd in virtualbox, but failed at configure with missing libunistring package. Would be great if you could try again.

**Comment by ejurgensen** [comment]
Ok, compiles now, but seems like there is another issue. On line 2068 argument 1 to process_directories is not initialized. Maybe it should be d->path and not path?

BTW have a look at scripts/freebsd_install_10.1.sh, maybe that will fix the configure of libunistring.

**Comment by chme** [comment]
Yes, it should be "d->path". Fixed it in the last commit.

> BTW have a look at scripts/freebsd_install_10.1.sh, maybe that will fix the configure of libunistring.

That's what i did. I had to change the line "sudo install --mode=755 scripts/freebsd_start_10.1.sh /usr/local/etc/rc.d/forked-daapd" into "sudo install -m 755 scripts/freebsd_start_10.1.sh /usr/local/etc/rc.d/forked-daapd". But ran into the missing libunistring error afterwards. Uncommenting the lines export lines did not help ...

**Comment by ejurgensen** [comment]
Excellent, thanks! Merged now. Tested it a bit with mPod and mPad, and there were no problems. Loading was pretty fast with my "medium" size library.

**Pull request merged**
