### PR TITLE
[wip] mpd protocol

### PR DESCRIPTION
**Pull request by chme**
It is in a very early stage, but I started working on the support for the mpd protocol (see #51).

By now forked-daapd excepts connections from mpd clients (on port 8800) and returns static responses for "status" and "currentsong". For all other commands it returns an error.

@ejurgensen it would be great if you could have a look at the approach i have taken. Any feedback welcome!

### CODE REVIEW

**Comment by chme** [comment]
Finally i think this is good for a first review. 

I did change a lot more in the existing code, compared to the first attempt. I tried to keep the logic in the most appropriate file and not to workaround the existing commands.

One major change is the introduction of the "filelist" table and the additional column "virtual_path" in the files and playlist table. This is done to show all files and playlist by using the mpd command "lsinfo" (e.g. with "mpc ls"). For real files the virtual_path equals the path prefixed with "/file:/" for streams it is the title prefixed with "/http:/" and for spotify it is constructed by "/spotify:/albumartist/album/title".

Another change is the introduction of the "player_queue" struct. Instead of returning "source_head" or "shuffle_head" from player.c and allowing the calling function to iterate over the items, which is not thread safe, the "player_queue" struct containing all queue information is returned by player.c.

And another change is, that filescanner.c now exposes the bulk-scan functionality, so that it can be triggered through a mpd command (mpc update). 

There is probably a lot that can be improved, i appreciate any feedback.

**Comment by ejurgensen** [comment]
This is really cool, I look forward to trying it!

Like you said, there are a lot of changes to the existing code, which is sometimes necessary - but it means it will take more time to review, and it also carries an increased likelihood that I will ask for some changes.

About the config file change: The individual artwork pr required a new config option, so the next release (for the RPi, at least) will require a config file update no matter what. I'm thinking of maybe including this config option as well, even though the release will probably be before I have this pr reviewed and merged - so there will be no actual mpd support. But that way users won't be required to do yet a config file update when this comes. But it depends - if you expect that more mpd config options are coming, then it's better to just wait until then. Let me know what you think.

**Comment by ejurgensen** [comment]
One other thing: I don't think I understood the point of the virtual_path? Can you help me with that? Also, how can it be in the playlist table, since a playlist can contain a mixture of items (well maybe not Spotify, but real files and http?)

**Comment by chme** [comment]
> But it depends - if you expect that more mpd config options are coming, then it's better to just wait until then. Let me know what you think.

The port number is the only important config option. Additional options would be to limit/restrict access to mpd commands like it is done in the mpd.conf file:

```
# Permissions #################################################################
# 
# If this setting is set, MPD will require password authorization. The password
# can setting can be specified multiple times for different password profiles.
# 
#password                        "password@read,add,control,admin"
#       
# This setting specifies the permissions a user has who has not yet logged in.
#       
#default_permissions             "read,add,control,admin"
# 
###############################################################################
```

I think, these can wait until this is supported in forked-daapd (i do not expect them to be implemented soon).

**Comment by chme** [comment]
Rebased on master, hope i resolved the conflicts in db.c correctly.

**Comment by ejurgensen** [comment]
Thanks, I began testing mpd some time ago, I hope to get back to you shortly with some comments. One advice I need: Do you know of a good iOS client? I tried MPoD, but it didn't work too well. Also: Is it so that mpd has no support for playlists? (maybe just MPoD?).

Two comments on the merge with db.c:
- you don't need to include the index in the upgrade path (so remove U_V16_CREATE_IDX_FILELIST), since they are auto-regenerated on upgrade
- I suppose it's possible to upgrade to just v15.2, since you are just expanding the database. So the current forked-daapd should be compatible? Of course the current version won't keep virtual_path and filelist updated, so maybe not... unless you maintained these with triggers?

**Comment by chme** [comment]
I only know of MPoD, but have not checked lately if there are others (my iOS device is quite outdated - still running iOS 5.1). With this first set of supported mpd commands, using full remote apps for mpd, will not work properly. I tested the two available mpd clients in the play store and both rely on commands that are not yet supported by forked-daapd. 

Regarding playlists: there is support in the mpd protocol (http://www.musicpd.org/doc/protocol/playlist_files.html). I am planning to add support for these in the next pr for the mpd protocol.

The main benefit of the implemented commands in this pr is, that it is now possible to have a simple webinterface (ympd) and a command line client (mpc) to control forked-daapd. With the python mpd client library (https://github.com/Mic92/python-mpd2) adding some push buttons to the rpi is now a lot easier.

Regarding the db update: i prefer a new major version, as the introduction of the virtual_path for playlists and files plus the new filelist table are quite significant. Using triggers to update the filelist table is - as far as i know - not possible, because a new or added file potentially leads to multiple inserts in the filelist table (one for the file and one for each parent directory).

**Comment by ejurgensen** [comment]
It seems that filelist could be auto-maintained with triggers as it is just a collection of files from the files table (F_FILE), playlists from the playlists table (F_PLAYLIST) and dirs from the inotify table (F_DIR). I don't think it would require multiple inserts for ordinary files (the dirs will come from inotify), but for Spotify you would need to have maybe 4 fixed inserts (container, artist, album and title) and for http 2 fixed inserts (container and title). I think it would be possible, but you would probably end up with a lot of triggers (3 tables x insert, update, delete + special Spotify and http insert/update = 13 triggers?).

I know I said I would be fine with a new table, but all the data in filelist sure seems very redundant, and it needs a bunch of code to stay in sync with the main tables. I'm trying to think of possible alternatives.

**Comment by ejurgensen** [comment]
Ok, so I've finally had time to put together detailed feedback on this. First of all, thank you for some excellent work, which I think will become very useful. There are a lot of changes to existing code, and I'll admit that there were parts, where I just didn't have the energy to analyze in depth and get a full understanding. So my level of feedback is a bit varied, as you will see.

filescanner.c:
753: Right now fd will segfault on a pipe, because virtual_path will be null. Scrap the first if() and make file:/ the default.
2016/2037: check if scan is already running (then ignore calls) - probably need a global state variable for that

db.c/db.h
Like I said, I'm not crazy about the redundancy of the filelist table, but I have yet to think of a better solution. So my plan is to merge it as it is, and maybe some day I will make some changes.
Why is F_URL not actually used?
free_pli: virtual_path is not free'd
1907: add a comment about filelist that it is used only for mpd
1927+1955: it would be simpler to use "INSERT OR IGNORE" and db_query_run()
1982: I would like mpd query's to have a mpd prefix: so db_build_query_filelist -> db_mpd_build_query_filelist
1982: this does not just build a query, like the others, but actually begins executing it (you should build -> start -> fetch -> end)
2011: mpd query (so like above)
2756/2767: some comments
2010/2028: cache_command copy paste error
4699: please add an id to the filelist table

dacp.c:
not sure what the pos changes are about?

player.c:
what is range_type and item_range - could you add comments?
please don't downgrade the log severity of the player_state messages
a little naming: some day fd might be better at video, so avoid "song" (eg songlength_ms could just be len_ms) - and I know, I haven't been too good at doing this either
what's the relationship between playingid and cur_playing?

mpd.c:
haven't reviewed it, but I noticed this error (sorry haven't got a better debug of it right now):
[2015-01-15 22:14:25] [DEBUG]     raop: Building RECORD for S
[2015-01-15 22:14:26] [DEBUG]     raop: RAOP audio latency is 4096
[2015-01-15 22:14:26] [DEBUG]     raop: Setting max_volume for device S to 4
[2015-01-15 22:14:27] [DEBUG]     raop: Building SET_PARAMETER for S
[2015-01-15 22:14:27] [  LOG]      mpd: Error from buffer event

Misc strange stuff in MPoD, which may have nothing to do with your work:
Duplicates in Album list (BRMC listed twice)
PSY sorted before Paul
01 sorted under A
No speaker selection (maybe not supported by mpd?)
No queue?
Directories and files in between each other (when browsing by file)
Two unknown albums which were empty

That's it, hope you can use it and when you have done some of the fixing up I'll merge it.

**Comment by chme** [comment]
Thanks for the thorough review. I will fix the issues you found. 

Did you come up with an idea to avoid the filelist table? I am starting to think it might be enough to add a virtual_path to the playlist and files table and generate the filelist view for mpd by using either the previously used query (with an sqlite extension) or simply iterating over files and playlists to determine the directories. If it is to slow, maybe using the daap cache would be possible?

I am also not so sure if prefixing local files with "file:" is a good idea as this differs from mpd. Some clients may rely on a relative path to get the cover art. Will have to check how mpd handles streams and remote files in the filelist view.

**Comment by ejurgensen** [comment]
I haven't come up with any alternative filelist ideas. If you can think of something more simple it would be great, but it is up to you, it is not crucial for me.

I'll be avoiding any major interfering changes until this pr is merged, so you don't need to rebase all the time.

**Comment by chme** [comment]
I made some progress on this one and hopefully addressed all issues you found.

Notable changes are:
* [df5b0f7] replaced the filelist db table with a filelist db view, build by a union select for files and playlists. I think this is the better approach, the view is automatically up to date and there is no need for any logic to keep it in sync with the files/pl tables. Performance on the rpi is ok, i rarely get timeouts due to long running requests with ympd. 
* [0c936c9] introduced a new global variable in filescanner.c to avoid triggering the update job multiple times.
* [63a480d] a little refactoring of the playback_start function (i hope this makes the code better understandable). Added some comments to clarify e. g. the use of item_range. I am not really happy with the implementation and my changes in player.c, but couldn't come up with a better solution. I hope the code comments make it clear, what my intentions for the changes are. 
* added support for some more mpd commands: search, find, list, playlistid

> No speaker selection (maybe not supported by mpd?)
No queue?

There is support for speaker selection in mpd ('outputs' command), but it is not yet implemented in mpd.c. To get the queue mpd offers different commands and not all are implemented yet. I guess MPoD uses one thats not supported. You can try again with the added commits, if MPoD uses the playlistid command, the queue should show up.

**Comment by ejurgensen** [comment]
Once again, great work! I've merged it now and hopefully we will hear from people using it in the near future. I myself will absolutely be trying these new capabilities.

I didn't have time to have a closer look at the db view, but to me it sounds like a good way to solve the problem.

As you can see, I tagged a release just recently. That was because I wanted a release with the iTunes fix, but before this. This change is large, which obviously always carries an increased risk of new bugs. So my plan is to first have it tested by people here, then I'll make an RPi release, see how that goes, and when all seems stable, forked-daapd with mpd support will become version 23.0.

**Pull request merged**
