### PR TITLE
Convert INSTALL document to markdown

### PR DESCRIPTION
**Pull request by marecabo**
This change converts the `INSTALL` document to markdown for improved readability.

closes https://github.com/ejurgensen/forked-daapd/issues/887

### CODE REVIEW

**Comment by ejurgensen** [comment]
Thanks for the contribution. Did you remove INSTALL and add INSTALL.md? The commit history seems to be lost, I think that is avoided if you use git mv to rename.

**Comment by marecabo** [comment]
Oh, yes, I did delete and add. I'll try git mv and see if it keeps the history.

**Comment by marecabo** [comment]
Okay, I noticed that even using `git mv` *and* changing the file in a single commit results in a delete and add operation instead of a rename (which makes sense somehow) so I separated the commits and now git picks up the full history of the file with:
```bash
git log --follow -p .\INSTALL.md
```

**Comment by ejurgensen** [comment]
Merged, thanks!

**Pull request merged**
