### PR TITLE
Modified to obtain compilation information from each files

### PR DESCRIPTION
**Pull request by zmatsuo**
Some music files have compilation information.
 (ex http://id3.org/iTunes%20Compilation%20Flag)
So, I try to read and use this information in forked-daapd.

### CODE REVIEW

**Comment by ejurgensen** [comment]
Thanks! If it the flag just takes the form 0 or 1, does it need a parser? Does it work if you just add it to the map like so:
{ "compilation",  1, mfi_offsetof(compilation),        NULL },

**Comment by zmatsuo** [comment]
I search specification of av_metadata_get(). But I can not find.
Is compilation key's value 0 or 1? I think yes.
But if av_metadata_get() returns other value, db include that value.
So next code is safety.
   mfi->compilation = compilation == 1 ? 1 : 0;

Too much care? how do you think?

**Comment by ejurgensen** [comment]
Ok, I've added support for this, but using the standard way used in forked-daapd. It's true that if the value is something else than 1 or 0, then that will go in the db (but only as an int value). That won't do any harm.

BTW av_metadata_get() is a deprecated ffmpeg function, so that is probably why you couldn't find it. forked-daapd will normally use av_dict_get().

**Comment by zmatsuo** [comment]
I see. great!
Thank you.

**Pull request closed without merging**
