### PR TITLE
Update player web interface v0.6.0

### PR DESCRIPTION
**Pull request by chme**
Changes:

- Update dependencies (npm, buima, ...)
- Add settings page for remote pairing/device verification
- Add settings page for Spotify login (currently login for libspotify still redirects to the admin page) and Last.fm login

All functionality from the admin page is now implemented in the player web interface.
(I am thinking about removing the separate admin page.)

Would be great if someone can check if device verification works from the settings page (i don't have access to a device that requires this).

### CODE REVIEW

**Comment by ejurgensen** [comment]
Very cool indeed!

I've tried device verification, and it works, but I did notice some confusing behavior. I went back and found out that it was also there before, so it isn't an issue with this PR. Well maybe since the context has changed it is a bit more confusing than before. Here's what I observed:

1. Start with the ATV unselected
2. Select the ATV in the web list of outputs (enable the check box)
3. The check box now automatically unselects (probably not clear to a user why that happens)
4. The ATV will now show a PIN code
5. Enter PIN code in web, press enter
6. No feedback to the user whether the operation succeeded

There is nothing in the UI telling the user that the check boxes actually indicate whether the device is selected, and now that there are other and better ways to see that it might be an idea to get rid of them? And just have some sort of button that triggers verification?

An additional observation related to the check boxes (also present previously):

1.- 4. Same as above
5. Don't enter PIN code, close browser
6. Open browser again, go to the settings again and put the check mark in the box
7. Nothing happens - verification is not triggered this time. Check mark is not removed automatically.
8. Remove check mark, and put it again
9. Now verification is triggered

**Comment by ejurgensen** [comment]
BTW an observation regarding the Spotify part of the settings: On my dev machine I normally build without spotify, but the settings page gives a warning on yellow background that "libspotify is not installed!" The message is both incorrect (I actually do have libspotify installed), and also a bit too "dramatic". I think it would be better to just show the Spotify options disabled/greyed out.

**Comment by chme** [comment]
Sure, it would be good to improve the usability. 

I have to admit, i don't remember how the whole verification process works. Would be great if you could check if my assumptions are correct:

- A device that requires verification is not identifiable (no special attribute/flag set)
- Verification process starts by enabling the device
- Enabling the device will change  `raop_session.state` to `RAOP_STATE_UNVERIFIED` (the device does not get enabled)
- Verification is done by calling `player_raop_verification_kickoff`with the pin, on success the device will hold an `auth_key`

Some questions:

- Can we identify the devices that will require device verification before enabling the device?

**Comment by ejurgensen** [comment]
My own memory on it is a bit hazy, but I think your understanding is very accurate. In raop.c `device->requires_auth` will initially be set based on the mdns announcement, but as I recall it was not 100% reliable. Also, it requires a connection attempt to establish if the stored auth_key is still valid. So the only sure-fire way of knowing is by trying to connect, I would say. Note that after a failed connection attempt `device->requires_auth` will be set to true. From reading the code I'm not sure if the auth_key also gets deleted, maybe it should.

I suppose the web would want some sort of callback with info about succes/failure. What are you thinking about for that? Maybe using the listener?

**Comment by chme** [comment]
I can think of three ways to achieve some kind of response:

1. Making the call to verify synchronous and return a success or error response to the client
2. Adding the verification result to the speaker/output as attribute (e. g. "last_action") and using the existing listener callback for speaker/output changes
3. Or a more generic approach by adding some sort of generic notification mechanism not tied to this one usecase (could be used for example also for filescanner progress).

    An idea i have is, that we could store important or interesting "events" in a new database table and send a notification if a new entry gets written into it. Some interesting "events" that are only visible in the log are for example:

    - The reason why a spotify song is not added to the library (due to it not being available any more / in the users country)
    - A notification if spotify playback stopped because playback for the same account was started on a different device

Do you have a preference or another idea how to approach this? And would it be okay to do this in a separate PR?

**Comment by chme** [comment]
I've modified the online settings to show a grey info box if Spotify or Last.fm is not enabled (see screenshot below).

---

Screenshot with Spotify and Last.fm disabled in configure:

image

**Comment by ejurgensen** [comment]
Yes, I agree that changing the verification stuff can be another PR. Device verification is not something done very often, so if you would rather put your time in other stuff I certainly understand that as well. Perhaps the simplest solution is to leave it as it is, but make the checkboxes more dumb. I.e. they don't change depending on whether the device is selected or not. They are initially always deselected, and if they are clicked, then you (re)enable the device + show the PIN input box.

With regard to the ways of getting a response, I'm not sure, but the generic one, number 3, sounds best. But why have permanent storage of the events - wouldn't memory be enough?

The updated Spotify/LastFM looks good!

**Comment by chme** [comment]
> make the checkboxes more dumb. I.e. they don't change depending on whether the device is selected or not. They are initially always deselected, and if they are clicked, then you (re)enable the device + show the PIN input box.

That might be confusing because activating the checkbox activates the speaker, if it is not a device that requires verification.

> But why have permanent storage of the events - wouldn't memory be enough?

It does not need to be persistent across a server restart, but there could potentially be a lot interesting events (especially if we want to make the scan a bit more transparent, e. g. the spotify events). Could potentially have a largish memory footprint. And a db table has the benefit, that we could query it, e. g. filtering by event types or severity.

**Comment by ejurgensen** [comment]
Another approach to the device verification could be to remove it from the settings entirely, and instead open it via the speaker selection dropdown. So the user would enable a speaker, and if the speaker then ends in the unverified state then display a PIN box. So that would be more like iTunes does it. But maybe it is difficult design-wise to have that stuff in the speaker selection?

**Comment by chme** [comment]
I tried to put the pin input into the speaker selection menu, but could not make it look good.
A version i have working is, that the the pin input for verification and pairing trigger a modal dialog (like the ones for details for album, etc.). It is nice especially for the paring, because you don't need to open a special page to input the pin and instead get notified directly. One problem with that is, that the need for feedback if paring/verification succeeded, is more important. So i am holding that back until the feedback/response stuff is implemented.

I will merge this current PR if you are fine with that.

**Comment by ejurgensen** [comment]
Yes, absolutely

**Pull request merged**
