### PR TITLE
Player web interface v0.8.0

### LINKED ISSUE #1025: web interface in iframe
Hi,

I'm trying to run forked-daapd as a hassio (home assistant) addon, and the daemon itself works fine but the web interface does not work in ingress.

Going directly to the 3689 port works, but when using ingress (loading the UI directly within home assistant's UI using an iframe) the href aren't prepended with the correct path :+1: 
```html
<iframe src="/api/hassio_ingress/<addon ID>//">
    ...
    <head>
        <link href="/player/css/app.css" rel="preload" as="style">
    </head>
</iframe>
```

The link for app.css (and all other resources) should here be /api/hassio_ingress/<addon ID>/player/css/app.css instead.
Is there some config I could add, or some change I could make when building the addon to make this behave as expected ?

Thank you

### LINKED ISSUE #1039: [web] Search results do not include audio books
Steps to reproduce:

1. Go to web player, 
2. Select the search icon
3. type in an author of an audiobook or a name of an audiobook
4. Press Enter

Results do not include any audiobook related info (e.g. when a `media_kind` is `audiobook`).

Expected to see results that include audiobooks.

In larger collections of audiobook, search is a critical feature to find the items quickly. Would improve user experience significantly.

### LINKED ISSUE #1047: [web] Make radio a top level tab
@chme it's great to have the radio tab with PR #1008 (also ref issue #1027), but I was a bit surprised to find under the Music tab. I think it would be better to have it as a top level tab, like Podcasts and Audiobooks. This is also the way it shown in Remote.

### LINKED ISSUE #1060: [web] Rename "About" menu item, since it has the update library buttons
I was trying to find the library update button, which was previously on the admin page. It took a while to find it, because it is now under "About", which I don't think is intuitive. The word "About" doesn't convey that there is functionality to be found. So I propose renaming the menu item to "Library", which is also the title of the page.

It would also be good if the README said where to find the update function (right now it says"You can do this by using “Update library” from the web interface.").

### LINKED ISSUE #1085: Minor issue with unexpected behavior with random playlist in Web frontend
I learned to love the smart random playlist feature recently added; but there is a problem with web frontend.
Steps to reproduce:
create a smart playlist with 100 random tracks: "random 100" {
    media_kind is music
    order by random desc
    limit 100
}

select that playlist (--> queue 1), start playing, then (cause you dont like that randon selection)
then select that playlist again (queue 2)

while the frontend still shows queue 1 even when playing queue 2 (the playlist just does not get updated); mpc playlist shows queue 2
When you select the trackinfo and than the playlist view again, the correct playlist (queue 2) gets displayed.

is there a way to update the display after selecting the playlist?

### PR DESCRIPTION
**Pull request by chme**
- Show cover artwork in album listings
- Make "Radio" a top level menu item (fixes #1047)
- Use the list of tracks shown for random playlists to fill the queue (closes #1087 + a change to only use the list of tracks if the playlist is random)
- Use relative paths in web interface (closes #973 and hopefully also fixes #1025)
- JSON API change to disallow caching of playlist tracks (fixes #1085)
- Add audiobooks author page
- Add search results for audiobooks and podcasts (fixes #1039)
- Refactor album and artist lists to reduce code duplication
- Allow sorting of the artists/albums list, add filter to only show local library (excludes artists/albums from Spotify)
- Rename "About" to "Update Library" to make it easier to find the option to rescan the library (closes #1060)

### CODE REVIEW

**Comment by chme** [comment]
@ejurgensen I have added a global setting as you recommended. I have added default values to `settings.c`, please take a look at that change. I also removed the default value handling for artwork sources and replaced it with fixed default values (setting the artwork sources in the configuration is not documented and my guess is that it is not used, correct me if I am wrong).

@whatdoineed2do Fetching artwork is quite expensive, so I think a setting is worth the effort. I made a change in the `CoverArtwork.vue` component, the creation of the generated image is now lazy (only created for images visible in the browser) and only happens if no image exists. The impact on performance should not be noticable

**Comment by chme** [comment]
Caching is kind of problematic in some places. In #1082 I have included a JSON API change (https://github.com/ejurgensen/forked-daapd/pull/1082/commits/0352539f8285ccc36432a79ccc72e7a5ccff2aed) that fixed it in my tests. The problem is the "Cache-Control" header forked-daapd sets. For playlists this was "private no-cache" in combination with "Last-Modified" header. This tells the browser to always check if a cached version can be used. The "Last-Modified" is the timestamp of the last rescan. Thus this did not work for random playlists (forked-daapd tells the browser that the cached version is still valid). The mentioned commit changes this and forked-daapd now sets "Cache-Control" to "no-store", which tells the browser to never cache the response.

**Comment by whatdoineed2do** [comment]
@chme would you consider adding the following patch?  This would solve one final problem with adding random playlists using the modal dialogue which uses the `playlist_id` and runs into the same problem whereby, from a playlist page, a `playlist modal` add would result in different tracks added.

Using the `playlist modal` from the name playlist page would still use the `playlist id`.

```
diff --git a/web-src/src/components/ModalDialogPlaylist.vue b/web-src/src/components/ModalDialogPlaylist.vue
index 3df472a6..ffd64970 100644
--- a/web-src/src/components/ModalDialogPlaylist.vue
+++ b/web-src/src/components/ModalDialogPlaylist.vue
@@ -44,7 +44,7 @@ import webapi from '@/webapi'
 
 export default {
   name: 'ModalDialogPlaylist',
-  props: ['show', 'playlist'],
+  props: ['show', 'playlist', 'tracks'],
 
   methods: {
     play: function () {
@@ -54,12 +54,20 @@ export default {
 
     queue_add: function () {
       this.$emit('close')
-      webapi.queue_add(this.playlist.uri)
+      if (this.tracks) {
+        webapi.queue_add(this.tracks.map(a => a.uri).join(','))
+      } else {
+        webapi.queue_add(this.playlist.uri)
+      }
     },
 
     queue_add_next: function () {
       this.$emit('close')
-      webapi.queue_add_next(this.playlist.uri)
+      if (this.tracks) {
+        webapi.queue_add(this.tracks.map(a => a.uri).join(','))
+      } else {
+        webapi.queue_add_next(this.playlist.uri)
+      }
     },
 
     open_playlist: function () {
diff --git a/web-src/src/pages/PagePlaylist.vue b/web-src/src/pages/PagePlaylist.vue
index 2ad88ae7..793ac16c 100644
--- a/web-src/src/pages/PagePlaylist.vue
+++ b/web-src/src/pages/PagePlaylist.vue
@@ -23,7 +23,7 @@
         </template>
       </list-item-track>
       <modal-dialog-track :show="show_details_modal" :track="selected_track" @close="show_details_modal = false" />
-      <modal-dialog-playlist :show="show_playlist_details_modal" :playlist="playlist" @close="show_playlist_details_modal = false" />
+      <modal-dialog-playlist :show="show_playlist_details_modal" :playlist="playlist" :tracks="tracks" @close="show_playlist_details_modal = false" />
     </template>
   </content-with-heading>
 </template>
```

**Comment by chme** [comment]
@whatdoineed2do yes, that patch makes sense, i'll add it to this PR. Thanks!

**Comment by ejurgensen** [comment]
> I have added default values to settings.c, please take a look at that change. I also removed the default value handling for artwork sources and replaced it with fixed default values (setting the artwork sources in the configuration is not documented and my guess is that it is not used, correct me if I am wrong).

Completely forgot to answer this @chme, sorry about that! You are right that the artwork config option isn't documented, and also isn't terribly important, but I actually think the default handler functions should stay. Maybe not surprising, since I added them :-)

The main reason is that I think we need a way to bridge the settings and the config file. I think a number of options need to be both places, both for transition reasons, but also because we should continue to offer both the user-frienldly db settings and the text-based "Linux way" config file. Having the ability to handle complex defaults is of course an added bonus.

**Comment by chme** [comment]
> The main reason is that I think we need a way to bridge the settings and the config file. I think a number of options need to be both places, both for transition reasons, but also because we should continue to offer both the user-frienldly db settings and the text-based "Linux way" config file. Having the ability to handle complex defaults is of course an added bonus.

I agree that there needs to be a way to transition or link config file settings to the DB settings.
I would like to see something more generic for that, instead of having functions for each setting to provide the value from the config file. I was thinking about something like defining a string path to the setting in the config file (e. g. "library.pipe_autostart" will get the value from the config file as default value for a "pipe_autostart" setting in the DB).

**Comment by ejurgensen** [comment]
> I was thinking about something like defining a string path to the setting in the config file (e. g. "library.pipe_autostart" will get the value from the config file as default value for a "pipe_autostart" setting in the DB).

Yes, I agree that would be a good solution

**Comment by chme** [comment]
I have added some additional functionality to the artists and albums list. It is now possible to sort e. g. the albums list by release date. If no objections, i will merge in the next days.

**Comment by ejurgensen** [comment]
Sounds good, I look forward to this. I’m thinking I will also make a new forked-daapd release with these improvements.

**Comment by ejurgensen** [comment]
I have installed the new version on my main RPi and it looks + works great! For my own use the easier way to find radio streams is a nice improvement. I also like the way you added filters/sorting to the listings.

A few minor observations, let me know if you want them in separate issues:

1. Click the search button, enter a search text, click Spotify. The search text disappears and you have to start over. This is not a new issue, but I noticed it again when trying the new version, so though I should mention it.
2. Click Music > Albums in a library with many albums. Scroll down towards the bottom. The artwork seems to load from the top, so it takes a very long before the artwork for the viewed items appears. In Remote artwork for the viewed items are prioritised, is that possible in the browser?
3. Spelling mistake in "Be aware that if you select more items than can be shown on your screen will result in the burger menu item to disapear." Suggestion for fixed + shorter text: "If you select more items than can be shown on your screen then the burger menu will disappear". Would of course be better if this couldn't happen, might be better to truncate the top level type items.
4. "About" is now "Update Library", but clicking it does not actually update library. I understand this is to make it easier to find, but naming it as an action without having an action seems odd to me - I would suggest just calling it "Library".

**Comment by chme** [comment]
@ejurgensen thanks for the feedback!

>     1. Click the search button, enter a search text, click Spotify. The search text disappears and you have to start over. This is not a new issue, but I noticed it again when trying the new version, so thought I should mention it.

The search with the last search query is triggered automatically when klicking the "Spotify" button in the search page. Only the text field was empty. I have fixed that, so now switching between the search in Spotify and local library keeps the search query in the text field.
 
>     2. Click Music > Albums in a library with many albums. Scroll down towards the bottom. The artwork seems to load from the top, so it takes very long before the artwork for the viewed items appears. In Remote artwork for the viewed items are prioritised, is that possible in the browser?

There are for sure possibilities to optimize this behavior. I would love to see images only loaded if they are visible a configurable amount of time. But I did not find a library that supports that (and as far as I can tell the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) that is used, does not support this out of the box).

>     3. Spelling mistake in "Be aware that if you select more items than can be shown on your screen will result in the burger menu item to disapear." Suggestion for fixed + shorter text: "If you select more items than can be shown on your screen then the burger menu will disappear". Would of course be better if this couldn't happen, might be better to truncate the top level type items.

Fixed with #1104 

>     4. "About" is now "Update Library", but clicking it does not actually update library. I understand this is to make it easier to find, but naming it as an action without having an action seems odd to me - I would suggest just calling it "Library".

I find "Library" confusing as a label that only shows some library stats. But I understand your point of view as well. I changed it, so now we have the "About" menu entry and a "Update library" menu entry. The later is now a action that opens a modal dialog to run the library rescan. You can find a screenshot in #1104 .

**Comment by ejurgensen** [comment]
Fantastic with the quick improvements in 0.8.1! I think the way you handled the "Update Library" issue is great.

I still have issues with the Spotify search. I think the reason you are not seeing it is that you press Enter after entering the search text. I didn't do that, since I figured pressing "Spotify" would act as a search button. So here is what I still observe:

1. Goto Search, enter a text, do not press Enter
2. Press Spotify -> text is gone (unexpected)
3. Enter text again, press Spotify -> nothing happens (also unexpected) -> you have to go back to the text field and press Enter

Maybe Library|Spotify should be above the input box so they don't appear as search buttons?

**Pull request merged**
