### PR TITLE
Support order-by/limit in smart playlists and support smartpl queries in JSON search endpoints

### PR DESCRIPTION
**Pull request by chme**
There are multiple changes in this pr (the changes all evolved around extending the JSON API for the web interface i am working on) but i hope it is fine to pr them together (if necessary, i can split them into separate prs). 

- Support for ORDER BY and LIMIT in smart playlists
- Support for HAVING clause in smart playlist query language (currently only useful for the json api for fetching albums/artists by their album/track count)
- Support for smart playlist query expressions in JSON API search endpoint
- New JSON API endpoints for getting a specific playlist, artist, album
- New JSON API endpoint to seek to a position in the currently playing track
- Add cache-control headers to some JSON API endpoints to allow browsers to cache results

The addition of ORDER BY and LIMIT in smart playlists require a database upgrade (v19.08). With these it is possible to create smart playlists for e. g.: the 100 last played tracks in descending order by the last time played.

Please take a special look at b5e6430, which fixes a wrong album count. I hope this was not on purpose (some kind of workaround).

### CODE REVIEW

**Comment by chme** [comment]
@ejurgensen I just noticed, that adding new columns to the playlist table requires a major db upgrade. Or alternatively the check in `db_query_fetch_pl` needs to be adjusted to allow the schema having more columns than the column map. What would you prefer?

**Comment by ejurgensen** [comment]
Made a quick review of the pr, for me it is fine to merge. It looks like a large-ish change, so I assume you have tested it well :-)

A cosmetic thing is that the "order by"-strings have different naming: order, orderby and order_by. Perhaps you could just use the same for all. I would prefer the simple "order".

**Comment by chme** [comment]
I changed the naming to "order" in most cases. And did some additional testing. Turns out there was a bug if "filescan_disable" is set to true (that's why i changed the default for limit to -1) and a memleak (missing free of the order clause). Also fixed a memleak that is in current master and is happening when parsing smart playlists with string operators.

I opted to keep the minor db version upgrade and added fa40f57 that allows running v19.08 with a previous forked-daapd version.

**Comment by ejurgensen** [comment]
Also merged, and also thanks!

**Pull request merged**
