### PR TITLE
[spotify] Remove scanning saved playlist with libspotify

### PR DESCRIPTION
**Pull request by chme**
With these changes scanning saved spotify albums/playlists require webapi access authorization. This simplifies the handling in spotify.c and reduces the usage of libspotify. 

I need to do some more testing, but it is good for a first review.

### CODE REVIEW

**Comment by chme** [comment]
Added an unrelated fix (status_lck mutex was not initialized/destroyed). So far it seems to work fine.

**Comment by ejurgensen** [comment]
The commits look nice and clean to me. Is it ready to merge? If so I will test it and merge if ok.

**Comment by chme** [comment]
Yes, it's good to be merged (given you don't find any issues)

**Comment by ejurgensen** [comment]
Didn't have much time to test, but the commits look fine, so hereby merged. Thanks :-)

**Pull request merged**
