### PR TITLE
[db,jsonapi] new "track artist" persistent id

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Restate:  this PR provides separation and notion of _track artist_ (via `songtrackartistid`) in db.  To support:
* group query for artist from db to include all artists as union of album artists and track artists
* extend search for _artist_ to cover track and album artists

----

Bug fix/edge condition - if we have `album_artist != artitst` and `artist` does not have an album oftheir own in db, then searches will never find `artist`.  This can be seen in:
```
select f.id,album_artist,artist,title,album,songalbumid,songartistid,compilation from files f;
id          album_artist  artist      title       album       songalbumid          songartistid         compilation
----------  ------------  ----------  ----------  ----------  -------------------  -------------------  -----------
1           foo           foo         efgh        album foo   1722214560191693504  2284445307090104385  0          
2           bar           bar         MNOP        foo/bar     1752720655991500595  1125938474926605440  0          
3           foo           foo         XYZ         foo/bar     1752720655991500595  2284445307090104385  0          
4           foo           foo         abcd        album foo   1722214560191693504  2284445307090104385  0          
5           Michael Jack  Michael Ja  Man in the  Bad         2384500295654811586  1322107677752712509  0          
7           Michael Jack  Michael Ja  Just Can't  Bad         2384500295654811586  1322107677752712509  0          
8           Various Arti  Marvin Gay  Let's Get   The Motown  1694630117637808949  8395563705718003786  1  
```
The artist `Marvin Gaye` does not have an album of its own - searches for `marvin` will NOT produce any results in returned `artist` json node as artist searches are based only on `album_artist` column.

The fix will return the `album_artist` persistent id - in this example click through the result would give info for "Various Artist" but this is acceptable IMHO to include the artist searched.
```
$ curl "http://localhost:3689/#/search/library?type=track,artist,album,playlist&query=marvin&limit=3&offset=0"
{
...
  "artists": {
    "items": [
      {
        "id": "8395563705718003786",
        "name": "Various Artists",
        "name_sort": "Various Artists",
        "album_count": 1,
        "track_count": 1,
        "length_ms": 2040,
        "uri": "library:artist:8395563705718003786",
        "artwork_url": "/artwork/group/8"
      }
    ],
    "total": 1,
    "offset": 0,
    "limit": 3
  },
...
}
```

### CODE REVIEW

**Comment by chme** [comment]
I agree, that it would be good to show artists that only appear on compilations. But showing "Various Artists" as a search result does not sound correct to me. This problem imo is not limited to the json api but instead a general issue in forked-daapd that happens on all clients (daap, mpd). 

Related to this problem is, that listing the albums/tracks of an artist does not show the compilations that this artist occurs in. What would imo be nice (regardless which client is used). 

A possible solution is to generate a persistent id for the artist tag and store it in the files table along side the albumartist persistent id (including the inserts/updates into the groups table). That would allow us to modify the queries for listing artists, etc. to include these (does have the drawback to make the queries more complex and less performant). In the web interface the search could then show the correct artist name instead of "Various artists" and link to this artists page.

**Comment by whatdoineed2do** [comment]
I think I agree with you.  However the change in this PR would need to go in along with the fix to correctly ID the artist from db.

The code now however does not let users find artists that only exist in a compilation which is confusing.

Can the dB cleanup / addition of songtrackartistid  be looked at as stage 2and separate to this?

**Comment by chme** [comment]
For me, getting a search result that does not match my search query is more confusing than missing the artist. Depending on how the files are tagged, it is not limited to showing the compilations artist, but could be some other artist name as well.

The sql queries to properly include the artist in addition to the album artist are not that simple. 
If i am not missing something, it would require something like the following, to get the artist persistent id with correct values for album count, etc.:

```sql
SELECT g.id, g.persistentid, f.album_artist, f.album_artist_sort, COUNT(f.id) [...] 
  FROM files f JOIN groups g ON f.songartistid = g.persistentid
  WHERE f.album_artist like [...]
  GROUP BY f.songartistid [...]
UNION
SELECT g.id, g.persistentid, f.artist, f.artist_sort, COUNT(f.id) [...] 
  FROM files f JOIN groups g ON f.<new artist persistent id field> = g.persistentid
  WHERE f.artist like [...]
  GROUP BY f.<new artist persistent id field> [...]
```

And that would still return wrong values for e. g. the album count field. I guess it would require a UNION ALL and an additional group by clause on the result set of the UNION to get the correct values.

**Comment by whatdoineed2do** [comment]
This set of changes seems to be good;  the work happens in 1ea2f4d2 but the SQL is now a little more complex.  There's some magic with the `unioncols` that tries to ensure that we pull back columns that may be part of the client request.

The `jsonapi` was updated to has new endpoint for better support to the `PageArtistTracks` page.

One note - when we get the results back from the db for our original case:
```
sqlite> Select id,artist,album_artist,album,title,songartistid,songtrackartistid,fname from files where album_artist like "%bar%" or artist like "%bar%";
id          artist      album_artist     album          title       songartistid         songtrackartistid    fname     
----------  ----------  ---------------  -------------  ----------  -------------------  -------------------  ----------
105         bar         Various Artists  album foo/bar  MNOP        8395563705718003786  1125938474926605440  bar-c.mp3
```
We STILL get the 'Various Artists' BUT now we do get the searched for artist.  This is a side effect because we can't easily split the `qp->where` clause in `db.c:db_build_query_group_artists()` as its set up in `httpd_jsonapi.c:search_artists()`'s `query_params.filter`
```
$ curl 'http://localhost:3689/api/search?type=artist&query=bar&media_kind=music&limit=3&offset=0' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   507  100   507    0     0   495k      0 --:--:-- --:--:-- --:--:--  495k
{
  "artists": {
    "items": [
      {
        "id": "1125938474926605440",
        "name": "bar",
        "name_sort": "bar",
        "album_count": 1,
        "track_count": 1,
        "length_ms": 3631,
        "uri": "library:artist:1125938474926605440",
        "artwork_url": "/artwork/group/144"
      },
      {
        "id": "8395563705718003786",
        "name": "Various Artists",
        "name_sort": "Various Artists",
        "album_count": 1,
        "track_count": 1,
        "length_ms": 3631,
        "uri": "library:artist:8395563705718003786",
        "artwork_url": "/artwork/group/137"
      }
    ],
    "total": 2,
    "offset": 0,
    "limit": 3
  }
}
```

**Pull request closed without merging**
