### PR TITLE
[jsonapi] potential memleaks on query_params.filter object

### PR DESCRIPTION
**Pull request by whatdoineed2do**
simple memleaks cleanup

### CODE REVIEW

**Comment by whatdoineed2do** [comment]
I don't know libevent well enough but valgrind shows this as a leak after I hit the web ui and then control-C the process
```
$ valgrind --leak-check=full --show-leak-kinds=definite $(pwd)/forked-daapd -f -c /etc/forked-daapd.conf -d 3
...
==19891== 
==19891== HEAP SUMMARY:
==19891==     in use at exit: 58,406 bytes in 315 blocks
==19891==   total heap usage: 110,653 allocs, 110,338 frees, 25,304,676 bytes allocated
==19891== 
==19891== 128 bytes in 1 blocks are definitely lost in loss record 250 of 292
==19891==    at 0x483880B: malloc (vg_replace_malloc.c:309)
==19891==    by 0x638E769: event_new (in /usr/lib64/libevent-2.1.so.6.0.2)
==19891==    by 0x4281C9: httpd_init (httpd.c:1731)
==19891==    by 0x40C90E: main (main.c:818)
==19891== 
==19891== LEAK SUMMARY:
==19891==    definitely lost: 128 bytes in 1 blocks
==19891==    indirectly lost: 0 bytes in 0 blocks
==19891==      possibly lost: 1,352 bytes in 18 blocks
==19891==    still reachable: 56,926 bytes in 296 blocks
==19891==                       of which reachable via heuristic:
==19891==                         newarray           : 1,536 bytes in 16 blocks
==19891==         suppressed: 0 bytes in 0 blocks
==19891== Reachable blocks (those to which a pointer was found) are not shown.
```

**Comment by ejurgensen** [comment]
Please remove the commit and make it as a separate pr. If freeing the base doesn’t free events then there will be similar memleaks other places.

**Comment by whatdoineed2do** [comment]
> Please remove the commit and make it as a separate pr. If freeing the base doesn’t free events then there will be similar memleaks other places.

Moved and done.

I was curious about this and took a quick look at where there are other `event_new` but `valgrind` doesn't flag any of those...

**Comment by chme** [comment]
Thanks!

**Pull request merged**
