### PR TITLE
Player web interface v0.7.2

### LINKED ISSUE #1003: [web] Minor shading error
@chme I noticed that if you scroll down a bit, and then select the speaker menu, the shading only covers some of the screen. See below. Reproduces in Chrome and Firefox.

shading_error

### LINKED ISSUE #1021: [web] Change device verification function
@chme when I looked at issue #1011 I could see that there were no listener notifications when a device failed during startup. So I looked at how to add that, and that gave me a strong urge to consolidate how the notifications are made by the player. Before they were triggered various places, both directly from outputs (raop.c), in the player "bottom half" functions and also after command_sync_exec(), so in the calling thread. I have changed that so they are now only triggered in the player.c, by the player thread, and via status_update() which is mostly used by "bottom halfs".

That meant I also had to change how device verification is implemented, and for that I have now added a "ouputs_device_authorize()" function that is more similar to other output commands in how it works. The player exposes it via a new player_speaker_authorize(), which in turn is exposed via the JSON PUT /api/outputs/xxxx endpoint.

So my suggestion is that you change the web to use player_speaker_authorize() instead of player_raop_verification_kickoff(). In fact the latter is a little bit broken by my recent changes since it doesn't trigger a listener notification anymore.

To ease your testing, I have added a possibility to mock device verification with the dummy output. You will notice that enabling an unverified device in the settings produces a red error box with the internal error from the toggle command. Maybe that could be more user friendly? The return value of player_speaker_enable() should provide the reason for the failure (-2 -> password/unverified).

### LINKED ISSUE #1027: Radios not showing as such in web UI
Hi,

I created a few m3u containing just the link to the http stream of the radio, and I'm getting these in the playlist tab and they do work fine.
However they do not show as internet radios, as I understand they should ? I don't even have radio showing at all in the interface.

None of these streams have any metadata defined unfortunately.
I did try setting radio_playlists to false explicitly, but that didn't change anything, the radio tab never appears.

### PR DESCRIPTION
**Pull request by chme**
- Show localized dates (PR #1000) 
- Fixes background overlay for bottom navbar dialog not covering the whole screen (closes #1003)
- Show cover artwork in album pages and lazy loading of cover artwork
- Use sass/scss for css files
- Add "Radio" tab to the music section (closes #1027)
- Switch to new JSON API for device verification (closes #1021)

Album page (desktop):
image

Album page (mobile):

### CODE REVIEW

**Comment by chme** [comment]
@whatdoineed2do @cdlenfert @ejurgensen I would appreciate, if you could give this a try and check if the album page displays correctly on iOS (see screenshots to how it should look like).

**Comment by whatdoineed2do** [comment]
Displays on IOS13/iphone7 

However but the artwork takes up most of the screen and if want to look at the tracks or play using the elipsis I've not got to scroll down - for me, this makes for an poor ux.

Similarly for the desktop, the image ends up occupying a large % of screen before we get any real info (tracks).

Can the artwork be made smaller?

**Comment by whatdoineed2do** [comment]
One other note - on the album page, we have the artwork displayed .. if we click on the elipsis, we then get the modal for the play/add next/add we have the artwork again

**Comment by ejurgensen** [comment]
Yes, I can confirm it displays as it should, and also great to have the dates localized + the background fix.

I would agree with @whatdoineed2do that it would be nice not to have to scroll down to start playback. It might also not be clear to the user that the tracks are listed below.

**Comment by whatdoineed2do** [comment]
Just given this ago on IOS 13.x / iphone and desktop - the space used by the image now is much more friendly/less overpowering now.

**Comment by chme** [comment]
This should now be good. I will leave the PR open a few days before merging, so if there are any issues, please report them.

@ejurgensen I have sneaked in a JSON API change https://github.com/ejurgensen/forked-daapd/pull/1008/commits/9616cfdf0cdadd2c43dd88f21d5c3968f9bef39e

**Pull request merged**
