### PR TITLE
Integrate device verification into the web interface

### PR DESCRIPTION
**Pull request by chme**
@ejurgensen i followed your advice to put a callback into the player to trigger the outputs update event. I think this is complete now, but have no way to test it.

### CODE REVIEW

**Comment by ejurgensen** [comment]
Made a test of this, it did trigger the PIN code on the ATV as it should, but no text field appeared in the web interface so I could enten the PIN. Is that because I am running it without libwebsockets? Or something else? Below you can see what the log file said.

[2017-11-18 21:13:43] [DEBUG]      web: Received select-outputs post request: { "outputs": [ "123642642794001" ] }
[2017-11-18 21:13:43] [DEBUG]   player: Speaker set: 1 speakers
[2017-11-18 21:13:43] [DEBUG]   player: Set 123642642794001 device 123642642794001
[2017-11-18 21:13:43] [DEBUG]   player: The AirPlay device 'Apple TV' is selected
[2017-11-18 21:13:43] [DEBUG]   player: Probing AirPlay device 'Apple TV'
[2017-11-18 21:13:43] [DEBUG]     raop: Building OPTIONS for 'Apple TV'
[2017-11-18 21:13:43] [DEBUG]   player: Set 123642642794001 device 0
[2017-11-18 21:13:43] [DEBUG]   player: The ALSA device 'Computer' is NOT selected
[2017-11-18 21:13:43] [DEBUG]      mpd: Listener callback called with event type 8.
[2017-11-18 21:13:43] [DEBUG]      mpd: Notify clients waiting for idle results: 8
[2017-11-18 21:13:43] [DEBUG]     raop: Building POST for 'Apple TV'
[2017-11-18 21:13:43] [  LOG]     raop: Starting device verification for 'Apple TV', please submit PIN via a *.verification file
[2017-11-18 21:13:44] [DEBUG]   player: Callback from AirPlay to device_probe_cb
[2017-11-18 21:13:44] [DEBUG]     main: Command has 0 pending events
[2017-11-18 21:13:44] [DEBUG]      mpd: Listener callback called with event type 8.
[2017-11-18 21:13:44] [DEBUG]      mpd: Notify clients waiting for idle results: 8
[2017-11-18 21:13:44] [DEBUG]      web: JSON api request: '/api/outputs'
[2017-11-18 21:13:44] [DEBUG]    httpd: Checking web interface authentication
[2017-11-18 21:13:44] [DEBUG]    httpd: Authentication successful

**Comment by chme** [comment]
Did the text field for the pin code appear after reloading the page? From the debug log it looks like, if the reloading of the outputs (without websockets this is directly triggered after calling `/api/select-outputs`) should have returned the necessary information to the web interface.

Can you check what the `output_device->requires_auth` and `output_device->auth_key` contain when calling `/api/outputs` (in httpd_json.c the function is `jsonapi_reply_outputs`). To show the text field the expected values are requires_auth == 1 and auth_key == NULL.

**Comment by ejurgensen** [comment]
You are right, it was because requires_auth was not set. It is set from mdns, but that is not always reliable if the ATV gets set to device verification after boot (which I did). I made this change to raop.c (https://github.com/ejurgensen/forked-daapd/commit/5315bdf83ef365af7890c2d225aa929adeaa5b8c) and then it worked.

I'm little unsure of the meaning of LISTENER_SPEAKER. In listener.h it says it means enabling/disabling, but your comment in player.c indicates it also has other meaning? Like verification success/failure?

**Comment by chme** [comment]
I did not want to add another event, so i extended the meaning of LISTENER_SPEAKER. It now means that a speaker got enabled/disabled or its verification status changed. I adjusted the comment in listener.c.

**Comment by ejurgensen** [comment]
What do you think about putting the LISTENER_SPEAKER notifications in the device callbacks in player.c? These ones: https://github.com/ejurgensen/forked-daapd/blob/master/src/player.c#L1391

Right now it is in speaker_set(), which is perhaps too early, because that means the listener will get notified of a change before it actually happens. If the listener then requests speaker state it might get a false result - the speaker may still be in the process of activating (and that might of course fail).

**Comment by chme** [comment]
The difficulty is, that a callback can be triggered multiple times (for each output). To prevent the event being triggered for each callback, it probably needs some logic in commands_exec_end.  I can give it a try.

**Comment by ejurgensen** [comment]
Ok. If you like I can merge this and the change you are thinking about can be its own PR?

**Comment by chme** [comment]
I found an easy solution. The speaker_set function is only called from the player_speaker_set command. The SPEAKER event is now triggered after the command finishes. It is now triggered in the calling thread (dacp, mpd or httpd) and not anymore in the player thread, but i do not think this makes a difference (might even be better as there is a little bit less load on the player thread).

This is now ready to be merged.

**Comment by ejurgensen** [comment]
Brilliant, thanks!

**Pull request merged**
