### PR TITLE
[streaming] support sending ICY metadata (title)

### PR DESCRIPTION
**Pull request by whatdoineed2do**
Closes https://github.com/ejurgensen/forked-daapd/issues/730

Support `Icy-MetaData` client requests on http streaming, sending song "`title` - `artist`" in the _metadata_  (in `StreamingTitle='....';` string) embedded at periodic periods (8192 fix byte intervals) in the MP3 audio stream.

Also fixes shutdown race conditions in streaming cleanup.

### CODE REVIEW

**Comment by whatdoineed2do** [comment]
To add a little context around this PR.

I use a Roku Soundbridge in one room to stream music from `forked-daapd` instead of using the raw DAAP protocol since using the single line scroll on the Roku and its physical up/down remote control is cumbersome when instead I can use the server's web interface to search/queue/control.

Without this PR the Soundbridge cannot display the title or artist of the current playing track.  This is also true for other applications (vlc, mpv etc) that we could use to stream.  Web browser's (firefox/safari) don't make use of/request ICY metadata.

To verify the playback/`ICY metadata` is sent correctly, we can use `mpv` and watch the output on change of track and to listen with no artifacts in the audio stream - a mismatched `icy-metaint` will result in audible pops/clicks every second or so in playback
```
$ mpv --display-tags=* http://localhost:3689/stream.mp3
Playing: http://localhost:3689/stream.mp3
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
File tags:
 encoder: Lavf58.12.100
AO: [pulse] 44100Hz stereo 2ch float
File tags:
 icy-name: My Music on beats
 icy-title: Bad - Michael Jackson
A: 00:00:12 / 00:00:13 (91%) Cache:  0s+30KB
File tags:
 icy-title: Lets Get It On - Marvin Gaye
A: 00:00:16 / 00:00:17 (92%) Cache:  1s+34KB
File tags:
 icy-title: Man in the Mirror - Michael Jackson
A: 00:00:21 / 00:00:22 (94%) Cache:  0s+30KB
```

**Comment by ejurgensen** [comment]
Yes, I think the aim of the PR is very sensible, I just haven't gotten around to reviewing it. I will have a look at it asap.

**Comment by ejurgensen** [comment]
I have trouble finding time for a proper review, so instead I suggest you go through it and fix typos plus missing capitalization. Also organize the code so that functions player thread functions are together, and httpd thread functions are together. The latter makes it easier to review. 

Then I will merge and hopefully find time for a review post the merge.

**Comment by whatdoineed2do** [comment]
All done.  The function arrangements should be ok I think - the 3 new functions that are grouped together directly above the existing `streaming_send_cb()` and they called from that method.

This code should be good functionally and stable - I've been using this on my own branch - streaming to my Roku SoundBridge on a fairly regular basis with no issues.

**Comment by ejurgensen** [comment]
Merged, thanks!

**Pull request merged**
