### PR TITLE
[scan] configuration option to follow symlinks

### PR DESCRIPTION
**Pull request by wolfmanx**
I have a lot of ´symlinks,which leads to duplicate entries and a lot of spam in the log.
By ignoring symlinks, real errors become visible again.
The default is to follow symlinks.

### CODE REVIEW

**Comment by ejurgensen** [comment]
I'm not so fond of negative return values that are not errors. Also not so happy about having config logic inside a utility function like read_attributes. Have you considered testing for S_ISLNK in the calling functions instead?

**Comment by wolfmanx** [comment]
I agree, it was more of a hacky suggestion.

In order to avoid excessive calls to lstat(3), I have extended the read_attributes prototype with an output parameter `is_link`.

**Comment by ejurgensen** [comment]
It seems read_attributes() already returns sb, where the ->st_mode reveals if it is a symlink. So it doesn't seem necessary to add an extra output value?

**Comment by wolfmanx** [comment]
That's what I thought at first :)

But in case of a symlink, `sb` is filled with the result of `stat`(3) not `lstat`(3), so it does not reveal the symlink. The whole point of `read_attributes` seems to be to get the real attributes and the resolved path.

You could do a strcmp(resolved_path, path), but that takes too long.
Merging `S_IFLNK` into `sb.st_mode` would be another option, but then we are talking about total obscurity :)
IMHO, adding a parameter is the better choice.

Just take your pick, which one you like best.

**Comment by ejurgensen** [comment]
Ah yes, I should have read the bottom of part read_attributes before I answered :-)

I agree that the parameter is the better choice. Thanks for your contribution.

**Pull request merged**
