### PR TITLE
Added support for libav/ffmpeg dual installs

### PR DESCRIPTION
**Pull request by sshambar**
I've been working a bit on getting transcode.c to work w/o using deprecated features, and find
myself having to check against various ffmpeg and libav versions.  In the process I found
that when both ffmpeg and libav are installed (on for eg FreeBSD), the configure checks really don't check consistently between headers and libraries.

So I fixed it.  I reordered the CPPFLAGS/LIBS variables so that later check prepend, and allow (for example) libav checks to work against libav/libavcodec/avcodec.h even when libavcodec/avcodec.h from ffmpeg is around (similarly for the libraries).  Optional features (which are checked later) now get there own flags and are ordered after required features.  Also added support for the alternate pkg-config names for libav (eg libavcodec-libav)

I also updated the libav checks so that they check functions against the headers (not just linking, as that gives incorrect results if another library has the symbol in the default path).  Also added
pkg-config checks for libspotify (oops, missed that in the commit msg), a more
robust check for ffmpeg vs libav, and made the resulting configure smaller using functions
rather than repeating embedded script.

Checked it against FreeBSD, Fedora and OSX, with various options, and checked correct compile/link against libav on FreeBSD when ffmpeg is in the default path (libav's include/libs under a "libav"
prefix).

Let me know if you have any problems compiling on any of your test targets :)

### CODE REVIEW

**Comment by sshambar** [comment]
BTW, as I'm creating code that's ffmpeg/libav version specific, I could go two routes:

1) Use version checks to use code added after a specific version...ie create a macro that handles both ffmpeg and libav versions and uses code only after it was introduced for those versions, eg:
```c
// this macro would take args (ffmpeg major, minor, micro, libav major, minor, micro)
#if LIBAVCODEC_VERSION_CHECK(57, 33, 100, 57, 5, 0)
// use codecparameters
#else
// use codec
#endif
```
2) I could add structure or function checks as needed to configure.ac, and use defines, eg:
```c
  AC_CHECK_MEMBERS([struct AVStream.codecpar]...
#if HAVE_STRUCT_AVSTREAM_CODECPAR
... etc
```
Do you have a preference on which style I should go with?  I'm not particular, but the version check (1) is a little cleaner from configure's standpoint (fewer checks), but the feature checks (2) make the code a little clearer as to what's actually being tested for in the conditional at the cost of a slower configure (but people might look at the code with "version x.y.z required for this", but not know why)

**Comment by ejurgensen** [comment]
Good you ask. This is an area where I may well reject PR's on a more subjective basis (style or my personal perception of complexity). Some background on that:

The favorite word in the dictionary of the ffmpeg/libav developers seems to be 'deprecated', so there is quite a lot of maintenance on this account. That means I need to be able to do it on a regular basis, which again means I need to feel comfortable with the implementation.

I definitely prefer your option 2. Once, forked-daapd did have extensive version checks, akin to your option 1. These kept growing, and sometimes also got nested, and the code hurt my eyes. So I got rid of those in favor of the current strategy, which is along these lines:

1. In transcode.c and artwork.c, clean code targeting new(ish) ffmpeg. Some ifdef's are hard to avoid, but they should primarily be for entire functions.
2. Favor feature checks over version checks. Not a 100% rule, for instance a workaround for a bug can require version checking. HAVE_FFMPEG is also basically a version check, so not optimal.
3. Backwards compability and compability with libav goes in ffmpeg-compat - so this is the place for any "dirty" stuff
4. Favor reduced code complexity over perfect compability

I think having ffmpeg and libav at the same time is exotic, marvelous and ... well, slightly crazy. This PR looks ok (still need to take a closer look at it), but don't expect a lot of adjustments to meet this use case.

**Comment by sshambar** [comment]
Cool, feature checks are pretty much how I've been going so far, so I won't have to change much :)

In defense of the patch, it makes testing between ffmpeg and libav really easy.  I added a feature switch (which isn't in the patch, although I could definitely add it) so on a dual install machine I can run "./configure --with-libav; make", and just like that I've compile/linked against libav "./configure; make" and instant compile/link against ffmpeg.   It makes tweaking code to work on both really easy!

**Comment by sshambar** [comment]
Updated to merge with master.  Should I add the "--with-libav" option (it's 2 lines :)

**Comment by ejurgensen** [comment]
Yes, "--with-libav" would be nice to have

**Comment by sshambar** [comment]
Option added.

**Comment by ejurgensen** [comment]
Merged, thanks

**Pull request merged**
